// <auto-generated />

#nullable disable

using MedicalDocumentationManager.Database.Contexts;
using MedicalDocumentationManager.Database.Contexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MedicalDocumentationManager.Database.Migrations
{
    [DbContext(typeof(MedicalDocumentationManagerDbContext))]
    [Migration("20240609150950_AlterTableSubscriptions")]
    partial class AlterTableSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressEntities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Houston",
                            State = "IL",
                            Street = "Pine St",
                            Zip = "59412"
                        },
                        new
                        {
                            Id = 2L,
                            City = "Phoenix",
                            State = "AZ",
                            Street = "Cedar Ln",
                            Zip = "28511"
                        },
                        new
                        {
                            Id = 3L,
                            City = "Phoenix",
                            State = "CA",
                            Street = "Oak St",
                            Zip = "62989"
                        },
                        new
                        {
                            Id = 4L,
                            City = "Chicago",
                            State = "CA",
                            Street = "Broadway",
                            Zip = "89195"
                        },
                        new
                        {
                            Id = 5L,
                            City = "New York",
                            State = "CA",
                            Street = "Oak St",
                            Zip = "55146"
                        },
                        new
                        {
                            Id = 6L,
                            City = "Phoenix",
                            State = "TX",
                            Street = "Elm St",
                            Zip = "17759"
                        },
                        new
                        {
                            Id = 7L,
                            City = "Philadelphia",
                            State = "CA",
                            Street = "Highland Ave",
                            Zip = "90566"
                        },
                        new
                        {
                            Id = 8L,
                            City = "Houston",
                            State = "NY",
                            Street = "Highland Ave",
                            Zip = "89579"
                        },
                        new
                        {
                            Id = 9L,
                            City = "Houston",
                            State = "TX",
                            Street = "Broadway",
                            Zip = "11700"
                        },
                        new
                        {
                            Id = 10L,
                            City = "Philadelphia",
                            State = "AZ",
                            Street = "Cedar Ln",
                            Zip = "85922"
                        },
                        new
                        {
                            Id = 11L,
                            City = "San Diego",
                            State = "TX",
                            Street = "Cedar Ln",
                            Zip = "41120"
                        },
                        new
                        {
                            Id = 12L,
                            City = "San Jose",
                            State = "TX",
                            Street = "Washington Ave",
                            Zip = "28375"
                        },
                        new
                        {
                            Id = 13L,
                            City = "San Diego",
                            State = "CA",
                            Street = "Washington Ave",
                            Zip = "56816"
                        },
                        new
                        {
                            Id = 14L,
                            City = "Phoenix",
                            State = "CA",
                            Street = "Maple Ave",
                            Zip = "67096"
                        },
                        new
                        {
                            Id = 15L,
                            City = "Chicago",
                            State = "IL",
                            Street = "Main St",
                            Zip = "43753"
                        },
                        new
                        {
                            Id = 16L,
                            City = "Philadelphia",
                            State = "TX",
                            Street = "Pine St",
                            Zip = "33124"
                        },
                        new
                        {
                            Id = 17L,
                            City = "San Jose",
                            State = "TX",
                            Street = "Washington Ave",
                            Zip = "51876"
                        },
                        new
                        {
                            Id = 18L,
                            City = "San Antonio",
                            State = "CA",
                            Street = "Pine St",
                            Zip = "40948"
                        },
                        new
                        {
                            Id = 19L,
                            City = "San Diego",
                            State = "CA",
                            Street = "Oak St",
                            Zip = "64937"
                        },
                        new
                        {
                            Id = 20L,
                            City = "Philadelphia",
                            State = "IL",
                            Street = "Sunset Blvd",
                            Zip = "24105"
                        },
                        new
                        {
                            Id = 21L,
                            City = "Los Angeles",
                            State = "TX",
                            Street = "Oak St",
                            Zip = "96933"
                        },
                        new
                        {
                            Id = 22L,
                            City = "San Jose",
                            State = "CA",
                            Street = "Elm St",
                            Zip = "80464"
                        },
                        new
                        {
                            Id = 23L,
                            City = "Los Angeles",
                            State = "AZ",
                            Street = "Elm St",
                            Zip = "71229"
                        },
                        new
                        {
                            Id = 24L,
                            City = "San Diego",
                            State = "TX",
                            Street = "Cedar Ln",
                            Zip = "29983"
                        },
                        new
                        {
                            Id = 25L,
                            City = "Houston",
                            State = "AZ",
                            Street = "Pine St",
                            Zip = "29319"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExperienceInYears")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("DoctorEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49a5c2b0-cc81-4a40-bbfc-d02b5bde249a"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1956, 7, 28),
                            Education = "Medical Degree",
                            Email = "emma.brown6@aol.com",
                            ExperienceInYears = 8L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-942-1352",
                            RoomNumber = "D-821",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("d584ab75-8bd8-4ab6-bf81-22ffccb7f43c"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1991, 10, 12),
                            Education = "Medical Degree",
                            Email = "michael.williams0@gmail.com",
                            ExperienceInYears = 28L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-999-567-7611",
                            RoomNumber = "C-313",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("6631aa0a-2474-4777-8c6a-92a439cf6672"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1950, 1, 21),
                            Education = "Medical Degree",
                            Email = "emma.brown4@gmail.com",
                            ExperienceInYears = 16L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-313-4352",
                            RoomNumber = "A-189",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("49e28d01-2067-4d9e-a086-556be1e39ed3"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1952, 11, 19),
                            Education = "Medical Degree",
                            Email = "james.jones9@yahoo.com",
                            ExperienceInYears = 16L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-666-534-8080",
                            RoomNumber = "C-448",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            AddressId = 7L,
                            BirthDate = new DateOnly(1985, 11, 23),
                            Education = "Medical Degree",
                            Email = "michael.williams3@hotmail.com",
                            ExperienceInYears = 12L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-666-978-1711",
                            RoomNumber = "E-172",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("63ce2675-2880-4359-a842-7d92a3e5d478"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1998, 4, 8),
                            Education = "Medical Degree",
                            Email = "john.smith8@gmail.com",
                            ExperienceInYears = 2L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-888-451-6312",
                            RoomNumber = "A-545",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("e592809c-495b-4a54-af87-ff2a4dc2c0f1"),
                            AddressId = 24L,
                            BirthDate = new DateOnly(1997, 8, 1),
                            Education = "Medical Degree",
                            Email = "emily.johnson4@outlook.com",
                            ExperienceInYears = 13L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-666-375-8159",
                            RoomNumber = "C-146",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("c17268dc-5e86-48c6-bf7f-bb0211a34597"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1986, 11, 28),
                            Education = "Medical Degree",
                            Email = "emily.johnson1@hotmail.com",
                            ExperienceInYears = 30L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-666-446-5712",
                            RoomNumber = "B-358",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("bd0177b8-41cc-44fb-9255-ea455e7c91be"),
                            AddressId = 7L,
                            BirthDate = new DateOnly(1976, 10, 23),
                            Education = "Medical Degree",
                            Email = "emily.johnson3@hotmail.com",
                            ExperienceInYears = 1L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-888-145-9442",
                            RoomNumber = "B-621",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("d967207e-5cf9-43a0-8dc5-88184da40fbd"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1997, 4, 12),
                            Education = "Medical Degree",
                            Email = "emily.johnson2@outlook.com",
                            ExperienceInYears = 23L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-888-791-7585",
                            RoomNumber = "C-150",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("81968a99-7398-4900-a6e5-9a1412171465"),
                            AddressId = 13L,
                            BirthDate = new DateOnly(1980, 10, 3),
                            Education = "Medical Degree",
                            Email = "emily.johnson7@aol.com",
                            ExperienceInYears = 6L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-666-406-7822",
                            RoomNumber = "A-492",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("40bc2fbd-e28a-4f9c-96e0-4c7e61cecb3b"),
                            AddressId = 5L,
                            BirthDate = new DateOnly(1961, 6, 13),
                            Education = "Medical Degree",
                            Email = "john.smith2@hotmail.com",
                            ExperienceInYears = 29L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-999-663-2419",
                            RoomNumber = "E-278",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("cfb1814f-64b4-4c28-817d-77530d91fc4b"),
                            AddressId = 12L,
                            BirthDate = new DateOnly(1964, 3, 21),
                            Education = "Medical Degree",
                            Email = "emma.brown4@outlook.com",
                            ExperienceInYears = 19L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-323-7491",
                            RoomNumber = "C-206",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("8f3aea52-ba1e-462a-8bf7-3c99d509e3d5"),
                            AddressId = 7L,
                            BirthDate = new DateOnly(1958, 12, 28),
                            Education = "Medical Degree",
                            Email = "emily.johnson8@gmail.com",
                            ExperienceInYears = 1L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-555-519-7797",
                            RoomNumber = "A-470",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("da630793-8f6d-456d-8c9b-6ee2d601e293"),
                            AddressId = 22L,
                            BirthDate = new DateOnly(1995, 11, 18),
                            Education = "Medical Degree",
                            Email = "emma.brown8@hotmail.com",
                            ExperienceInYears = 26L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-999-364-1479",
                            RoomNumber = "A-484",
                            Specialization = "Cardiology"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecordEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31b8864f-a82c-45e7-8cdb-e7f379916b79"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1969),
                            DoctorId = new Guid("49a5c2b0-cc81-4a40-bbfc-d02b5bde249a"),
                            PatientId = new Guid("7aa0a526-a3ea-4f8a-a7f4-83d129145930"),
                            Record = "Medical record 1 for patient 7aa0a526-a3ea-4f8a-a7f4-83d129145930 and doctor 49a5c2b0-cc81-4a40-bbfc-d02b5bde249a",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1970)
                        },
                        new
                        {
                            Id = new Guid("ca25957b-d494-4d9d-bd23-e48b31b01690"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1976),
                            DoctorId = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            PatientId = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            Record = "Medical record 2 for patient d0115f46-dda7-4f2c-b2e5-3a7bb37760cd and doctor 70178d73-1891-4eeb-b1d7-e73b4b55ff63",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1977)
                        },
                        new
                        {
                            Id = new Guid("0c046b8d-a551-4fd3-aceb-074b82ffb4a8"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1982),
                            DoctorId = new Guid("bd0177b8-41cc-44fb-9255-ea455e7c91be"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            Record = "Medical record 3 for patient 27aa99e5-7810-4fec-ab4c-bff7034f1f63 and doctor bd0177b8-41cc-44fb-9255-ea455e7c91be",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1983)
                        },
                        new
                        {
                            Id = new Guid("108ac2c9-d18d-418b-b7d9-994130446ed0"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1987),
                            DoctorId = new Guid("bd0177b8-41cc-44fb-9255-ea455e7c91be"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            Record = "Medical record 4 for patient b4749c5a-ebcd-4c16-acef-e2b3bc11adcb and doctor bd0177b8-41cc-44fb-9255-ea455e7c91be",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1987)
                        },
                        new
                        {
                            Id = new Guid("aaf9fc1a-4568-4d7e-b67b-3bd1c4cc8723"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1992),
                            DoctorId = new Guid("da630793-8f6d-456d-8c9b-6ee2d601e293"),
                            PatientId = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            Record = "Medical record 5 for patient d0115f46-dda7-4f2c-b2e5-3a7bb37760cd and doctor da630793-8f6d-456d-8c9b-6ee2d601e293",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1992)
                        },
                        new
                        {
                            Id = new Guid("b7449f37-34c2-4691-bd25-b2d136ad48bf"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1997),
                            DoctorId = new Guid("49a5c2b0-cc81-4a40-bbfc-d02b5bde249a"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            Record = "Medical record 6 for patient 27aa99e5-7810-4fec-ab4c-bff7034f1f63 and doctor 49a5c2b0-cc81-4a40-bbfc-d02b5bde249a",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(1997)
                        },
                        new
                        {
                            Id = new Guid("2d034be3-c1ca-46f9-a140-9d0cd7cae1f2"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2004),
                            DoctorId = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            Record = "Medical record 7 for patient b9993fbc-df24-4ff8-82d4-d2c71ac9a52e and doctor 70178d73-1891-4eeb-b1d7-e73b4b55ff63",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2004)
                        },
                        new
                        {
                            Id = new Guid("cf4c8a2c-6641-4cf3-b637-224e01439d1f"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2009),
                            DoctorId = new Guid("6631aa0a-2474-4777-8c6a-92a439cf6672"),
                            PatientId = new Guid("b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c"),
                            Record = "Medical record 8 for patient b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c and doctor 6631aa0a-2474-4777-8c6a-92a439cf6672",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2010)
                        },
                        new
                        {
                            Id = new Guid("ce814387-a5fd-493b-b140-ec4909daaabf"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2013),
                            DoctorId = new Guid("bd0177b8-41cc-44fb-9255-ea455e7c91be"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            Record = "Medical record 9 for patient b9993fbc-df24-4ff8-82d4-d2c71ac9a52e and doctor bd0177b8-41cc-44fb-9255-ea455e7c91be",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2013)
                        },
                        new
                        {
                            Id = new Guid("1dcc8a35-cf12-4415-b663-f70aa65b2c9d"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2019),
                            DoctorId = new Guid("8f3aea52-ba1e-462a-8bf7-3c99d509e3d5"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            Record = "Medical record 10 for patient 27aa99e5-7810-4fec-ab4c-bff7034f1f63 and doctor 8f3aea52-ba1e-462a-8bf7-3c99d509e3d5",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2019)
                        },
                        new
                        {
                            Id = new Guid("dee1c798-c4e2-4c93-b4eb-f589cb66ba72"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2024),
                            DoctorId = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            Record = "Medical record 11 for patient 0b00c1de-5038-4aba-a635-8c8de68c92a2 and doctor 70178d73-1891-4eeb-b1d7-e73b4b55ff63",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2024)
                        },
                        new
                        {
                            Id = new Guid("105d5675-08a4-4c9f-836d-bdb854eb768d"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2028),
                            DoctorId = new Guid("8f3aea52-ba1e-462a-8bf7-3c99d509e3d5"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            Record = "Medical record 12 for patient b4749c5a-ebcd-4c16-acef-e2b3bc11adcb and doctor 8f3aea52-ba1e-462a-8bf7-3c99d509e3d5",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2029)
                        },
                        new
                        {
                            Id = new Guid("9ad502c0-f6ed-4218-bc5a-c312540f8ede"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2034),
                            DoctorId = new Guid("cfb1814f-64b4-4c28-817d-77530d91fc4b"),
                            PatientId = new Guid("cc573f43-b2b2-4f81-bd93-2755b5f9a8f5"),
                            Record = "Medical record 13 for patient cc573f43-b2b2-4f81-bd93-2755b5f9a8f5 and doctor cfb1814f-64b4-4c28-817d-77530d91fc4b",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2034)
                        },
                        new
                        {
                            Id = new Guid("605d9a42-dcdb-44b5-abeb-42561d787886"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2039),
                            DoctorId = new Guid("d584ab75-8bd8-4ab6-bf81-22ffccb7f43c"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            Record = "Medical record 14 for patient 27aa99e5-7810-4fec-ab4c-bff7034f1f63 and doctor d584ab75-8bd8-4ab6-bf81-22ffccb7f43c",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2039)
                        },
                        new
                        {
                            Id = new Guid("53a3cfc2-cb2d-4bb7-859f-b7c2b39fd06c"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2046),
                            DoctorId = new Guid("6631aa0a-2474-4777-8c6a-92a439cf6672"),
                            PatientId = new Guid("5bf4f189-f9ea-4341-99f7-7df0c5085cca"),
                            Record = "Medical record 15 for patient 5bf4f189-f9ea-4341-99f7-7df0c5085cca and doctor 6631aa0a-2474-4777-8c6a-92a439cf6672",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2046)
                        },
                        new
                        {
                            Id = new Guid("b19e9788-a9e1-4219-89e9-8b94f2bda161"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2058),
                            DoctorId = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            PatientId = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            Record = "Medical record 16 for patient d0115f46-dda7-4f2c-b2e5-3a7bb37760cd and doctor 70178d73-1891-4eeb-b1d7-e73b4b55ff63",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2058)
                        },
                        new
                        {
                            Id = new Guid("3429bfdb-3329-4c36-8100-92aef6c397af"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2063),
                            DoctorId = new Guid("63ce2675-2880-4359-a842-7d92a3e5d478"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            Record = "Medical record 17 for patient 0b7db7b1-31ca-44b2-9113-9b969130b4f3 and doctor 63ce2675-2880-4359-a842-7d92a3e5d478",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2063)
                        },
                        new
                        {
                            Id = new Guid("94f20bb9-db5e-4d5d-870b-a5c8a957a952"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2068),
                            DoctorId = new Guid("8f3aea52-ba1e-462a-8bf7-3c99d509e3d5"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            Record = "Medical record 18 for patient aeb8aba4-7483-4001-9d9c-d005e9be32f0 and doctor 8f3aea52-ba1e-462a-8bf7-3c99d509e3d5",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2069)
                        },
                        new
                        {
                            Id = new Guid("0935d907-18d7-4c61-b8f1-931477040f9e"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2073),
                            DoctorId = new Guid("8f3aea52-ba1e-462a-8bf7-3c99d509e3d5"),
                            PatientId = new Guid("13315216-3e0a-4c15-a6a8-fcdb85f9224c"),
                            Record = "Medical record 19 for patient 13315216-3e0a-4c15-a6a8-fcdb85f9224c and doctor 8f3aea52-ba1e-462a-8bf7-3c99d509e3d5",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2073)
                        },
                        new
                        {
                            Id = new Guid("0d2a9c25-3e6e-483d-a5c0-2547d5748934"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2078),
                            DoctorId = new Guid("70178d73-1891-4eeb-b1d7-e73b4b55ff63"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            Record = "Medical record 20 for patient a2b616ce-0588-4fb9-8fcb-eca1d8a22570 and doctor 70178d73-1891-4eeb-b1d7-e73b4b55ff63",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2078)
                        },
                        new
                        {
                            Id = new Guid("18a56a17-d8f2-4ca3-8c2c-521b0901c8e2"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2082),
                            DoctorId = new Guid("cfb1814f-64b4-4c28-817d-77530d91fc4b"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            Record = "Medical record 21 for patient b9993fbc-df24-4ff8-82d4-d2c71ac9a52e and doctor cfb1814f-64b4-4c28-817d-77530d91fc4b",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2083)
                        },
                        new
                        {
                            Id = new Guid("0ecd7d76-e6be-4670-a244-e6aa4a4ba521"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2087),
                            DoctorId = new Guid("cfb1814f-64b4-4c28-817d-77530d91fc4b"),
                            PatientId = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            Record = "Medical record 22 for patient 8d8128db-4e79-49a6-b473-8ac2abf64d83 and doctor cfb1814f-64b4-4c28-817d-77530d91fc4b",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2087)
                        },
                        new
                        {
                            Id = new Guid("c9a86cef-3fcf-42dd-95e5-9f259d34829a"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2093),
                            DoctorId = new Guid("bd0177b8-41cc-44fb-9255-ea455e7c91be"),
                            PatientId = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            Record = "Medical record 23 for patient 8d8128db-4e79-49a6-b473-8ac2abf64d83 and doctor bd0177b8-41cc-44fb-9255-ea455e7c91be",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2093)
                        },
                        new
                        {
                            Id = new Guid("c0e98bac-aaa0-4292-a6f3-79f32b8b5548"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2097),
                            DoctorId = new Guid("d584ab75-8bd8-4ab6-bf81-22ffccb7f43c"),
                            PatientId = new Guid("cc573f43-b2b2-4f81-bd93-2755b5f9a8f5"),
                            Record = "Medical record 24 for patient cc573f43-b2b2-4f81-bd93-2755b5f9a8f5 and doctor d584ab75-8bd8-4ab6-bf81-22ffccb7f43c",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2098)
                        },
                        new
                        {
                            Id = new Guid("bedf1488-76ea-49e5-b68c-b651434e005b"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2101),
                            DoctorId = new Guid("d584ab75-8bd8-4ab6-bf81-22ffccb7f43c"),
                            PatientId = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            Record = "Medical record 25 for patient 8d8128db-4e79-49a6-b473-8ac2abf64d83 and doctor d584ab75-8bd8-4ab6-bf81-22ffccb7f43c",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2102)
                        },
                        new
                        {
                            Id = new Guid("7d98a5f3-c3b6-4805-92fa-7727100a1d57"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2105),
                            DoctorId = new Guid("6631aa0a-2474-4777-8c6a-92a439cf6672"),
                            PatientId = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            Record = "Medical record 26 for patient d0115f46-dda7-4f2c-b2e5-3a7bb37760cd and doctor 6631aa0a-2474-4777-8c6a-92a439cf6672",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2106)
                        },
                        new
                        {
                            Id = new Guid("aa65dd8a-868c-40ca-9587-819f774ee3b3"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2110),
                            DoctorId = new Guid("e592809c-495b-4a54-af87-ff2a4dc2c0f1"),
                            PatientId = new Guid("b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c"),
                            Record = "Medical record 27 for patient b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c and doctor e592809c-495b-4a54-af87-ff2a4dc2c0f1",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2111)
                        },
                        new
                        {
                            Id = new Guid("c78980c0-9309-4158-af41-d3cc509d5f09"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2115),
                            DoctorId = new Guid("d967207e-5cf9-43a0-8dc5-88184da40fbd"),
                            PatientId = new Guid("b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c"),
                            Record = "Medical record 28 for patient b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c and doctor d967207e-5cf9-43a0-8dc5-88184da40fbd",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2115)
                        },
                        new
                        {
                            Id = new Guid("aba2d3e0-5a65-415c-b288-a2379b3e5585"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2119),
                            DoctorId = new Guid("da630793-8f6d-456d-8c9b-6ee2d601e293"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            Record = "Medical record 29 for patient 27aa99e5-7810-4fec-ab4c-bff7034f1f63 and doctor da630793-8f6d-456d-8c9b-6ee2d601e293",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2119)
                        },
                        new
                        {
                            Id = new Guid("feadd605-be98-4f27-8513-2e90d9e331f0"),
                            CreatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2124),
                            DoctorId = new Guid("49a5c2b0-cc81-4a40-bbfc-d02b5bde249a"),
                            PatientId = new Guid("7aa0a526-a3ea-4f8a-a7f4-83d129145930"),
                            Record = "Medical record 30 for patient 7aa0a526-a3ea-4f8a-a7f4-83d129145930 and doctor 49a5c2b0-cc81-4a40-bbfc-d02b5bde249a",
                            UpdatedAt = new DateTime(2024, 6, 9, 15, 9, 50, 448, DateTimeKind.Utc).AddTicks(2124)
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InsurancePolicyNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("PatientEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            AddressId = 5L,
                            BirthDate = new DateOnly(1960, 12, 16),
                            Email = "ethan.jackson2@outlook.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "637449363",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-222-418-9073"
                        },
                        new
                        {
                            Id = new Guid("cc573f43-b2b2-4f81-bd93-2755b5f9a8f5"),
                            AddressId = 1L,
                            BirthDate = new DateOnly(1963, 1, 10),
                            Email = "isabella.martinez6@yahoo.com",
                            FullName = "Isabella Martinez",
                            InsurancePolicyNumber = "364696528",
                            InsuranceProvider = "Anthem",
                            PhoneNumber = "+1-222-927-5891"
                        },
                        new
                        {
                            Id = new Guid("b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1969, 8, 10),
                            Email = "william.wilson1@yahoo.com",
                            FullName = "William Wilson",
                            InsurancePolicyNumber = "176908483",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-222-138-2085"
                        },
                        new
                        {
                            Id = new Guid("13315216-3e0a-4c15-a6a8-fcdb85f9224c"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1989, 1, 16),
                            Email = "amelia.clark0@hotmail.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "470661119",
                            InsuranceProvider = "BlueCross",
                            PhoneNumber = "+1-444-480-1763"
                        },
                        new
                        {
                            Id = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            AddressId = 18L,
                            BirthDate = new DateOnly(1975, 10, 16),
                            Email = "olivia.davis9@outlook.com",
                            FullName = "Olivia Davis",
                            InsurancePolicyNumber = "731210957",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-111-329-4695"
                        },
                        new
                        {
                            Id = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1983, 5, 26),
                            Email = "daniel.johnson7@yahoo.com",
                            FullName = "Daniel Johnson",
                            InsurancePolicyNumber = "885532910",
                            InsuranceProvider = "Molina Healthcare",
                            PhoneNumber = "+1-111-912-2804"
                        },
                        new
                        {
                            Id = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            AddressId = 22L,
                            BirthDate = new DateOnly(1983, 6, 13),
                            Email = "isabella.martinez9@aol.com",
                            FullName = "Isabella Martinez",
                            InsurancePolicyNumber = "559334818",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-222-253-8147"
                        },
                        new
                        {
                            Id = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1994, 10, 11),
                            Email = "ava.white4@aol.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "242645711",
                            InsuranceProvider = "UnitedHealthcare",
                            PhoneNumber = "+1-333-834-3648"
                        },
                        new
                        {
                            Id = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            AddressId = 10L,
                            BirthDate = new DateOnly(1997, 10, 20),
                            Email = "liam.anderson1@yahoo.com",
                            FullName = "Liam Anderson",
                            InsurancePolicyNumber = "283103060",
                            InsuranceProvider = "UnitedHealthcare",
                            PhoneNumber = "+1-111-487-3876"
                        },
                        new
                        {
                            Id = new Guid("4941f913-50d9-478c-8023-47ca581018b5"),
                            AddressId = 6L,
                            BirthDate = new DateOnly(1965, 5, 3),
                            Email = "isabella.martinez3@gmail.com",
                            FullName = "Isabella Martinez",
                            InsurancePolicyNumber = "359509772",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-111-586-7391"
                        },
                        new
                        {
                            Id = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            AddressId = 17L,
                            BirthDate = new DateOnly(1993, 1, 18),
                            Email = "ethan.jackson9@aol.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "870700416",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-444-937-7637"
                        },
                        new
                        {
                            Id = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            AddressId = 21L,
                            BirthDate = new DateOnly(1983, 12, 13),
                            Email = "amelia.clark4@aol.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "367660253",
                            InsuranceProvider = "Aetna",
                            PhoneNumber = "+1-222-305-7904"
                        },
                        new
                        {
                            Id = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            AddressId = 11L,
                            BirthDate = new DateOnly(1974, 2, 22),
                            Email = "daniel.johnson2@hotmail.com",
                            FullName = "Daniel Johnson",
                            InsurancePolicyNumber = "866395060",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-111-871-6640"
                        },
                        new
                        {
                            Id = new Guid("5bf4f189-f9ea-4341-99f7-7df0c5085cca"),
                            AddressId = 15L,
                            BirthDate = new DateOnly(1974, 4, 20),
                            Email = "amelia.clark3@outlook.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "346720637",
                            InsuranceProvider = "Friday Health Plans",
                            PhoneNumber = "+1-222-677-1723"
                        },
                        new
                        {
                            Id = new Guid("7aa0a526-a3ea-4f8a-a7f4-83d129145930"),
                            AddressId = 18L,
                            BirthDate = new DateOnly(1963, 3, 16),
                            Email = "sophia.taylor3@outlook.com",
                            FullName = "Sophia Taylor",
                            InsurancePolicyNumber = "626979715",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-444-206-2857"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("SubscriptionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MedicalRecordId = new Guid("dee1c798-c4e2-4c93-b4eb-f589cb66ba72"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 2L,
                            MedicalRecordId = new Guid("53a3cfc2-cb2d-4bb7-859f-b7c2b39fd06c"),
                            PatientId = new Guid("4941f913-50d9-478c-8023-47ca581018b5"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 3L,
                            MedicalRecordId = new Guid("3429bfdb-3329-4c36-8100-92aef6c397af"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 4L,
                            MedicalRecordId = new Guid("9ad502c0-f6ed-4218-bc5a-c312540f8ede"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 5L,
                            MedicalRecordId = new Guid("c9a86cef-3fcf-42dd-95e5-9f259d34829a"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 6L,
                            MedicalRecordId = new Guid("2d034be3-c1ca-46f9-a140-9d0cd7cae1f2"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 7L,
                            MedicalRecordId = new Guid("53a3cfc2-cb2d-4bb7-859f-b7c2b39fd06c"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 8L,
                            MedicalRecordId = new Guid("0c046b8d-a551-4fd3-aceb-074b82ffb4a8"),
                            PatientId = new Guid("13315216-3e0a-4c15-a6a8-fcdb85f9224c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 9L,
                            MedicalRecordId = new Guid("feadd605-be98-4f27-8513-2e90d9e331f0"),
                            PatientId = new Guid("5bf4f189-f9ea-4341-99f7-7df0c5085cca"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 10L,
                            MedicalRecordId = new Guid("ce814387-a5fd-493b-b140-ec4909daaabf"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 11L,
                            MedicalRecordId = new Guid("ca25957b-d494-4d9d-bd23-e48b31b01690"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 12L,
                            MedicalRecordId = new Guid("b7449f37-34c2-4691-bd25-b2d136ad48bf"),
                            PatientId = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 13L,
                            MedicalRecordId = new Guid("dee1c798-c4e2-4c93-b4eb-f589cb66ba72"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 14L,
                            MedicalRecordId = new Guid("c9a86cef-3fcf-42dd-95e5-9f259d34829a"),
                            PatientId = new Guid("a2b616ce-0588-4fb9-8fcb-eca1d8a22570"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 15L,
                            MedicalRecordId = new Guid("31b8864f-a82c-45e7-8cdb-e7f379916b79"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 16L,
                            MedicalRecordId = new Guid("9ad502c0-f6ed-4218-bc5a-c312540f8ede"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 17L,
                            MedicalRecordId = new Guid("0935d907-18d7-4c61-b8f1-931477040f9e"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 18L,
                            MedicalRecordId = new Guid("0d2a9c25-3e6e-483d-a5c0-2547d5748934"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 19L,
                            MedicalRecordId = new Guid("cf4c8a2c-6641-4cf3-b637-224e01439d1f"),
                            PatientId = new Guid("b55b9b0a-5e2d-4c7c-b4d1-7bc4724f069c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 20L,
                            MedicalRecordId = new Guid("94f20bb9-db5e-4d5d-870b-a5c8a957a952"),
                            PatientId = new Guid("8d8128db-4e79-49a6-b473-8ac2abf64d83"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 21L,
                            MedicalRecordId = new Guid("0935d907-18d7-4c61-b8f1-931477040f9e"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 22L,
                            MedicalRecordId = new Guid("c78980c0-9309-4158-af41-d3cc509d5f09"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 23L,
                            MedicalRecordId = new Guid("1dcc8a35-cf12-4415-b663-f70aa65b2c9d"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 24L,
                            MedicalRecordId = new Guid("c0e98bac-aaa0-4292-a6f3-79f32b8b5548"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 25L,
                            MedicalRecordId = new Guid("108ac2c9-d18d-418b-b7d9-994130446ed0"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 26L,
                            MedicalRecordId = new Guid("c78980c0-9309-4158-af41-d3cc509d5f09"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 27L,
                            MedicalRecordId = new Guid("2d034be3-c1ca-46f9-a140-9d0cd7cae1f2"),
                            PatientId = new Guid("cc573f43-b2b2-4f81-bd93-2755b5f9a8f5"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 28L,
                            MedicalRecordId = new Guid("108ac2c9-d18d-418b-b7d9-994130446ed0"),
                            PatientId = new Guid("d0115f46-dda7-4f2c-b2e5-3a7bb37760cd"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 29L,
                            MedicalRecordId = new Guid("aba2d3e0-5a65-415c-b288-a2379b3e5585"),
                            PatientId = new Guid("13315216-3e0a-4c15-a6a8-fcdb85f9224c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 30L,
                            MedicalRecordId = new Guid("18a56a17-d8f2-4ca3-8c2c-521b0901c8e2"),
                            PatientId = new Guid("13315216-3e0a-4c15-a6a8-fcdb85f9224c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 31L,
                            MedicalRecordId = new Guid("31b8864f-a82c-45e7-8cdb-e7f379916b79"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 32L,
                            MedicalRecordId = new Guid("b7449f37-34c2-4691-bd25-b2d136ad48bf"),
                            PatientId = new Guid("5bf4f189-f9ea-4341-99f7-7df0c5085cca"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 33L,
                            MedicalRecordId = new Guid("c78980c0-9309-4158-af41-d3cc509d5f09"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 34L,
                            MedicalRecordId = new Guid("605d9a42-dcdb-44b5-abeb-42561d787886"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 35L,
                            MedicalRecordId = new Guid("aba2d3e0-5a65-415c-b288-a2379b3e5585"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 36L,
                            MedicalRecordId = new Guid("0935d907-18d7-4c61-b8f1-931477040f9e"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 37L,
                            MedicalRecordId = new Guid("108ac2c9-d18d-418b-b7d9-994130446ed0"),
                            PatientId = new Guid("b9993fbc-df24-4ff8-82d4-d2c71ac9a52e"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 38L,
                            MedicalRecordId = new Guid("c9a86cef-3fcf-42dd-95e5-9f259d34829a"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 39L,
                            MedicalRecordId = new Guid("7d98a5f3-c3b6-4805-92fa-7727100a1d57"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 40L,
                            MedicalRecordId = new Guid("2d034be3-c1ca-46f9-a140-9d0cd7cae1f2"),
                            PatientId = new Guid("b4749c5a-ebcd-4c16-acef-e2b3bc11adcb"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 41L,
                            MedicalRecordId = new Guid("605d9a42-dcdb-44b5-abeb-42561d787886"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 42L,
                            MedicalRecordId = new Guid("0ecd7d76-e6be-4670-a244-e6aa4a4ba521"),
                            PatientId = new Guid("aeb8aba4-7483-4001-9d9c-d005e9be32f0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 43L,
                            MedicalRecordId = new Guid("aba2d3e0-5a65-415c-b288-a2379b3e5585"),
                            PatientId = new Guid("0b7db7b1-31ca-44b2-9113-9b969130b4f3"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 44L,
                            MedicalRecordId = new Guid("0c046b8d-a551-4fd3-aceb-074b82ffb4a8"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 45L,
                            MedicalRecordId = new Guid("dee1c798-c4e2-4c93-b4eb-f589cb66ba72"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 46L,
                            MedicalRecordId = new Guid("aaf9fc1a-4568-4d7e-b67b-3bd1c4cc8723"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 47L,
                            MedicalRecordId = new Guid("feadd605-be98-4f27-8513-2e90d9e331f0"),
                            PatientId = new Guid("0b00c1de-5038-4aba-a635-8c8de68c92a2"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 48L,
                            MedicalRecordId = new Guid("0ecd7d76-e6be-4670-a244-e6aa4a4ba521"),
                            PatientId = new Guid("5bf4f189-f9ea-4341-99f7-7df0c5085cca"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 49L,
                            MedicalRecordId = new Guid("dee1c798-c4e2-4c93-b4eb-f589cb66ba72"),
                            PatientId = new Guid("27aa99e5-7810-4fec-ab4c-bff7034f1f63"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 50L,
                            MedicalRecordId = new Guid("31b8864f-a82c-45e7-8cdb-e7f379916b79"),
                            PatientId = new Guid("4941f913-50d9-478c-8023-47ca581018b5"),
                            SubscriptionType = "Observer"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Doctors")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.DoctorEntity", "DoctorEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DoctorEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Patients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", "MedicalRecordEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecordEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
