// <auto-generated />

#nullable disable

using MedicalDocumentationManager.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MedicalDocumentationManager.Database.Migrations
{
    [DbContext(typeof(MedicalDocumentationManagerDbContext))]
    [Migration("20240610082650_AlterTableAddress")]
    partial class AlterTableAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Street", "City", "State", "Zip")
                        .IsUnique();

                    b.ToTable("AddressEntities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "New York",
                            State = "TX",
                            Street = "Cedar Ln",
                            Zip = "62938"
                        },
                        new
                        {
                            Id = 2L,
                            City = "Chicago",
                            State = "NY",
                            Street = "Washington Ave",
                            Zip = "63525"
                        },
                        new
                        {
                            Id = 3L,
                            City = "San Antonio",
                            State = "TX",
                            Street = "Oak St",
                            Zip = "28391"
                        },
                        new
                        {
                            Id = 4L,
                            City = "Philadelphia",
                            State = "TX",
                            Street = "Maple Ave",
                            Zip = "31653"
                        },
                        new
                        {
                            Id = 5L,
                            City = "San Jose",
                            State = "CA",
                            Street = "Oak St",
                            Zip = "30857"
                        },
                        new
                        {
                            Id = 6L,
                            City = "Houston",
                            State = "TX",
                            Street = "Pine St",
                            Zip = "87519"
                        },
                        new
                        {
                            Id = 7L,
                            City = "Los Angeles",
                            State = "TX",
                            Street = "Main St",
                            Zip = "79545"
                        },
                        new
                        {
                            Id = 8L,
                            City = "Houston",
                            State = "TX",
                            Street = "Maple Ave",
                            Zip = "37241"
                        },
                        new
                        {
                            Id = 9L,
                            City = "Phoenix",
                            State = "IL",
                            Street = "Washington Ave",
                            Zip = "95257"
                        },
                        new
                        {
                            Id = 10L,
                            City = "San Diego",
                            State = "CA",
                            Street = "Highland Ave",
                            Zip = "64316"
                        },
                        new
                        {
                            Id = 11L,
                            City = "Philadelphia",
                            State = "CA",
                            Street = "Broadway",
                            Zip = "96286"
                        },
                        new
                        {
                            Id = 12L,
                            City = "Houston",
                            State = "TX",
                            Street = "Washington Ave",
                            Zip = "33430"
                        },
                        new
                        {
                            Id = 13L,
                            City = "San Jose",
                            State = "NY",
                            Street = "Pine St",
                            Zip = "66242"
                        },
                        new
                        {
                            Id = 14L,
                            City = "Philadelphia",
                            State = "IL",
                            Street = "Washington Ave",
                            Zip = "83399"
                        },
                        new
                        {
                            Id = 15L,
                            City = "San Antonio",
                            State = "CA",
                            Street = "Sunset Blvd",
                            Zip = "47465"
                        },
                        new
                        {
                            Id = 16L,
                            City = "Philadelphia",
                            State = "TX",
                            Street = "Maple Ave",
                            Zip = "11116"
                        },
                        new
                        {
                            Id = 17L,
                            City = "Philadelphia",
                            State = "TX",
                            Street = "Pine St",
                            Zip = "58277"
                        },
                        new
                        {
                            Id = 18L,
                            City = "Houston",
                            State = "IL",
                            Street = "Main St",
                            Zip = "48687"
                        },
                        new
                        {
                            Id = 19L,
                            City = "San Diego",
                            State = "PA",
                            Street = "Cedar Ln",
                            Zip = "33206"
                        },
                        new
                        {
                            Id = 20L,
                            City = "New York",
                            State = "TX",
                            Street = "Elm St",
                            Zip = "49897"
                        },
                        new
                        {
                            Id = 21L,
                            City = "Phoenix",
                            State = "TX",
                            Street = "Maple Ave",
                            Zip = "25255"
                        },
                        new
                        {
                            Id = 22L,
                            City = "Dallas",
                            State = "AZ",
                            Street = "Broadway",
                            Zip = "13349"
                        },
                        new
                        {
                            Id = 23L,
                            City = "San Diego",
                            State = "CA",
                            Street = "Oak St",
                            Zip = "18220"
                        },
                        new
                        {
                            Id = 24L,
                            City = "Los Angeles",
                            State = "IL",
                            Street = "Highland Ave",
                            Zip = "10741"
                        },
                        new
                        {
                            Id = 25L,
                            City = "San Jose",
                            State = "PA",
                            Street = "Pine St",
                            Zip = "68823"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExperienceInYears")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("DoctorEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42951efb-c4ad-4cb7-8ccd-6747c3842f4c"),
                            AddressId = 15L,
                            BirthDate = new DateOnly(1977, 11, 14),
                            Education = "Medical Degree",
                            Email = "john.smith2@yahoo.com",
                            ExperienceInYears = 17L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-555-693-4716",
                            RoomNumber = "A-226",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("9494b0d4-ae59-4812-9b25-05fee61fc6e5"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1987, 5, 12),
                            Education = "Medical Degree",
                            Email = "james.jones7@hotmail.com",
                            ExperienceInYears = 17L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-555-206-5187",
                            RoomNumber = "D-456",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("ebea2a4a-f8c3-4d85-ade2-4a9aafc1f1e8"),
                            AddressId = 13L,
                            BirthDate = new DateOnly(1987, 4, 20),
                            Education = "Medical Degree",
                            Email = "emily.johnson6@outlook.com",
                            ExperienceInYears = 6L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-666-584-9061",
                            RoomNumber = "E-396",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("013cb794-a21b-45a5-a678-5dcce26be03e"),
                            AddressId = 1L,
                            BirthDate = new DateOnly(1997, 7, 24),
                            Education = "Medical Degree",
                            Email = "james.jones7@aol.com",
                            ExperienceInYears = 4L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-999-361-2192",
                            RoomNumber = "D-502",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("ef0222ff-5282-4b29-a62f-71d853c0aaff"),
                            AddressId = 16L,
                            BirthDate = new DateOnly(1976, 4, 21),
                            Education = "Medical Degree",
                            Email = "emma.brown0@aol.com",
                            ExperienceInYears = 9L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-757-1347",
                            RoomNumber = "D-458",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("63ada4f7-602e-4452-8b87-37ca17b66de8"),
                            AddressId = 19L,
                            BirthDate = new DateOnly(1958, 6, 5),
                            Education = "Medical Degree",
                            Email = "emma.brown5@yahoo.com",
                            ExperienceInYears = 18L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-834-2483",
                            RoomNumber = "D-319",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("22576f99-412a-4956-aec6-bf1da155fffc"),
                            AddressId = 23L,
                            BirthDate = new DateOnly(1996, 2, 12),
                            Education = "Medical Degree",
                            Email = "michael.williams2@outlook.com",
                            ExperienceInYears = 26L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-777-237-4183",
                            RoomNumber = "E-366",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("ceb037f8-430e-43e5-a394-786daf2891f2"),
                            AddressId = 10L,
                            BirthDate = new DateOnly(1974, 6, 15),
                            Education = "Medical Degree",
                            Email = "emma.brown0@hotmail.com",
                            ExperienceInYears = 25L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-888-529-7395",
                            RoomNumber = "E-561",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("31e273ed-bb90-4ecb-9b04-b4da014f895e"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1955, 2, 11),
                            Education = "Medical Degree",
                            Email = "emily.johnson1@yahoo.com",
                            ExperienceInYears = 28L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-999-547-2482",
                            RoomNumber = "B-437",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("1e12dcc5-2e38-44d3-9f5a-073574fc6922"),
                            AddressId = 3L,
                            BirthDate = new DateOnly(1969, 6, 9),
                            Education = "Medical Degree",
                            Email = "emma.brown3@hotmail.com",
                            ExperienceInYears = 2L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-327-5395",
                            RoomNumber = "C-833",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1984, 3, 20),
                            Education = "Medical Degree",
                            Email = "emma.brown2@gmail.com",
                            ExperienceInYears = 30L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-777-584-7011",
                            RoomNumber = "D-439",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("1345f6de-2771-46d4-9f77-a4e05956c87e"),
                            AddressId = 12L,
                            BirthDate = new DateOnly(1965, 9, 6),
                            Education = "Medical Degree",
                            Email = "john.smith7@gmail.com",
                            ExperienceInYears = 23L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-888-592-4121",
                            RoomNumber = "B-344",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("e5e17ffd-ed56-4335-bcc1-205e6364efa8"),
                            AddressId = 7L,
                            BirthDate = new DateOnly(1951, 11, 5),
                            Education = "Medical Degree",
                            Email = "emily.johnson4@hotmail.com",
                            ExperienceInYears = 16L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-888-826-1597",
                            RoomNumber = "C-551",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3"),
                            AddressId = 23L,
                            BirthDate = new DateOnly(1988, 12, 13),
                            Education = "Medical Degree",
                            Email = "john.smith0@yahoo.com",
                            ExperienceInYears = 18L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-999-981-8955",
                            RoomNumber = "E-271",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("5cc0d903-59fd-48b7-9e14-6495a0e78a2d"),
                            AddressId = 6L,
                            BirthDate = new DateOnly(1990, 1, 9),
                            Education = "Medical Degree",
                            Email = "james.jones7@outlook.com",
                            ExperienceInYears = 11L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-666-262-8868",
                            RoomNumber = "B-372",
                            Specialization = "Orthopedics"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Record")
                        .IsUnique();

                    b.ToTable("MedicalRecordEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90252700-eb4c-441a-b1fa-cf68e16dd826"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6039),
                            DoctorId = new Guid("e5e17ffd-ed56-4335-bcc1-205e6364efa8"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            Record = "Medical record 1 for patient e073a299-2f0c-4584-bf4c-2278e935cdd8 and doctor e5e17ffd-ed56-4335-bcc1-205e6364efa8",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6342)
                        },
                        new
                        {
                            Id = new Guid("043d5d32-578b-4281-85c4-948ba1b8d48c"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6461),
                            DoctorId = new Guid("42951efb-c4ad-4cb7-8ccd-6747c3842f4c"),
                            PatientId = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            Record = "Medical record 2 for patient 6b036ff0-f402-489e-bad7-f88dd8f23a81 and doctor 42951efb-c4ad-4cb7-8ccd-6747c3842f4c",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6461)
                        },
                        new
                        {
                            Id = new Guid("4a12586c-2f89-42b7-b697-4f1260055486"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6473),
                            DoctorId = new Guid("42951efb-c4ad-4cb7-8ccd-6747c3842f4c"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            Record = "Medical record 3 for patient 910c3e7e-a55f-4844-b5cd-ce831e0fa095 and doctor 42951efb-c4ad-4cb7-8ccd-6747c3842f4c",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6474)
                        },
                        new
                        {
                            Id = new Guid("4a2c65cf-e17d-404f-9795-bd72fd725375"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6485),
                            DoctorId = new Guid("22576f99-412a-4956-aec6-bf1da155fffc"),
                            PatientId = new Guid("87e46f1c-885c-442e-b445-8d734797deeb"),
                            Record = "Medical record 4 for patient 87e46f1c-885c-442e-b445-8d734797deeb and doctor 22576f99-412a-4956-aec6-bf1da155fffc",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6486)
                        },
                        new
                        {
                            Id = new Guid("bd59dabd-3396-47eb-8faa-5790bbeda62b"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6497),
                            DoctorId = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            Record = "Medical record 5 for patient ed2b29cc-0fa4-42dc-b373-e3800af239ef and doctor bd080fc2-856e-416e-a698-90a7e5bda48a",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6497)
                        },
                        new
                        {
                            Id = new Guid("3037466f-e974-48c8-98f2-fb823ba1a833"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6623),
                            DoctorId = new Guid("e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            Record = "Medical record 6 for patient 460dbf3b-0312-4da5-895e-86834eb43b43 and doctor e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6624)
                        },
                        new
                        {
                            Id = new Guid("25aaf1c2-4e2b-4946-b2f4-f2034e8002de"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6652),
                            DoctorId = new Guid("e5e17ffd-ed56-4335-bcc1-205e6364efa8"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            Record = "Medical record 7 for patient 293a3eb3-7212-424a-bec5-d6b37f51841c and doctor e5e17ffd-ed56-4335-bcc1-205e6364efa8",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6653)
                        },
                        new
                        {
                            Id = new Guid("9cd0a48c-8bab-4ccb-a0e1-f6a01d4acfbf"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6662),
                            DoctorId = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            Record = "Medical record 8 for patient 910c3e7e-a55f-4844-b5cd-ce831e0fa095 and doctor bd080fc2-856e-416e-a698-90a7e5bda48a",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6663)
                        },
                        new
                        {
                            Id = new Guid("e607ebfa-fa1f-48d0-833b-b848ea923eca"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6670),
                            DoctorId = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            Record = "Medical record 9 for patient 460dbf3b-0312-4da5-895e-86834eb43b43 and doctor bd080fc2-856e-416e-a698-90a7e5bda48a",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6671)
                        },
                        new
                        {
                            Id = new Guid("6eb8aa5b-33b8-4c99-9e04-0af0be9cda0c"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6684),
                            DoctorId = new Guid("e5e17ffd-ed56-4335-bcc1-205e6364efa8"),
                            PatientId = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            Record = "Medical record 10 for patient a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0 and doctor e5e17ffd-ed56-4335-bcc1-205e6364efa8",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6685)
                        },
                        new
                        {
                            Id = new Guid("cc832aa3-44ae-4310-ae9b-3b08ec8fdcf9"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6692),
                            DoctorId = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            PatientId = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            Record = "Medical record 11 for patient a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0 and doctor bd080fc2-856e-416e-a698-90a7e5bda48a",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6693)
                        },
                        new
                        {
                            Id = new Guid("8c69d425-f59a-4770-a495-5a47d3225e4b"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6703),
                            DoctorId = new Guid("42951efb-c4ad-4cb7-8ccd-6747c3842f4c"),
                            PatientId = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            Record = "Medical record 12 for patient af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8 and doctor 42951efb-c4ad-4cb7-8ccd-6747c3842f4c",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6703)
                        },
                        new
                        {
                            Id = new Guid("5e3c7a5e-9d95-4200-8c4f-1bec92a0aafa"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6714),
                            DoctorId = new Guid("013cb794-a21b-45a5-a678-5dcce26be03e"),
                            PatientId = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            Record = "Medical record 13 for patient 6b036ff0-f402-489e-bad7-f88dd8f23a81 and doctor 013cb794-a21b-45a5-a678-5dcce26be03e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6715)
                        },
                        new
                        {
                            Id = new Guid("09a59ed7-016a-4fe2-a030-d77db56e53f1"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6723),
                            DoctorId = new Guid("bd080fc2-856e-416e-a698-90a7e5bda48a"),
                            PatientId = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            Record = "Medical record 14 for patient a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0 and doctor bd080fc2-856e-416e-a698-90a7e5bda48a",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6724)
                        },
                        new
                        {
                            Id = new Guid("692f03b9-ffcc-4a1e-96f8-2dd0e802023d"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6739),
                            DoctorId = new Guid("013cb794-a21b-45a5-a678-5dcce26be03e"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            Record = "Medical record 15 for patient e073a299-2f0c-4584-bf4c-2278e935cdd8 and doctor 013cb794-a21b-45a5-a678-5dcce26be03e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6740)
                        },
                        new
                        {
                            Id = new Guid("5898d1f4-ec6f-4634-bd5d-b3ec2fd508ad"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6750),
                            DoctorId = new Guid("013cb794-a21b-45a5-a678-5dcce26be03e"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            Record = "Medical record 16 for patient 0f9e953b-5402-42f6-ab5e-3badc7ea1309 and doctor 013cb794-a21b-45a5-a678-5dcce26be03e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6751)
                        },
                        new
                        {
                            Id = new Guid("08dffb4a-2a7e-47a3-98b3-0caa774a297a"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6759),
                            DoctorId = new Guid("1345f6de-2771-46d4-9f77-a4e05956c87e"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            Record = "Medical record 17 for patient ed2b29cc-0fa4-42dc-b373-e3800af239ef and doctor 1345f6de-2771-46d4-9f77-a4e05956c87e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6760)
                        },
                        new
                        {
                            Id = new Guid("4046602e-2e70-469f-8b56-096a360bd0ff"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6772),
                            DoctorId = new Guid("31e273ed-bb90-4ecb-9b04-b4da014f895e"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            Record = "Medical record 18 for patient ed2b29cc-0fa4-42dc-b373-e3800af239ef and doctor 31e273ed-bb90-4ecb-9b04-b4da014f895e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6772)
                        },
                        new
                        {
                            Id = new Guid("33111f91-72f3-4287-a135-e8c3935e51c3"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6782),
                            DoctorId = new Guid("ef0222ff-5282-4b29-a62f-71d853c0aaff"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            Record = "Medical record 19 for patient 460dbf3b-0312-4da5-895e-86834eb43b43 and doctor ef0222ff-5282-4b29-a62f-71d853c0aaff",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6783)
                        },
                        new
                        {
                            Id = new Guid("6893e409-cd81-443d-93cf-ce5f962f2412"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6790),
                            DoctorId = new Guid("1345f6de-2771-46d4-9f77-a4e05956c87e"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            Record = "Medical record 20 for patient 0f9e953b-5402-42f6-ab5e-3badc7ea1309 and doctor 1345f6de-2771-46d4-9f77-a4e05956c87e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6791)
                        },
                        new
                        {
                            Id = new Guid("7c177960-96ae-4418-a3dc-3e42cf399ec0"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6802),
                            DoctorId = new Guid("5cc0d903-59fd-48b7-9e14-6495a0e78a2d"),
                            PatientId = new Guid("8fb4f8c8-32d2-4cba-8fc5-33463f65fffa"),
                            Record = "Medical record 21 for patient 8fb4f8c8-32d2-4cba-8fc5-33463f65fffa and doctor 5cc0d903-59fd-48b7-9e14-6495a0e78a2d",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6803)
                        },
                        new
                        {
                            Id = new Guid("43c2d659-876f-4d60-b974-62778c8bdf8f"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6810),
                            DoctorId = new Guid("013cb794-a21b-45a5-a678-5dcce26be03e"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            Record = "Medical record 22 for patient 0f9e953b-5402-42f6-ab5e-3badc7ea1309 and doctor 013cb794-a21b-45a5-a678-5dcce26be03e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6811)
                        },
                        new
                        {
                            Id = new Guid("eaeca881-df6d-441d-a31a-af0ee0bbfaa1"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6824),
                            DoctorId = new Guid("ceb037f8-430e-43e5-a394-786daf2891f2"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            Record = "Medical record 23 for patient ed2b29cc-0fa4-42dc-b373-e3800af239ef and doctor ceb037f8-430e-43e5-a394-786daf2891f2",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6825)
                        },
                        new
                        {
                            Id = new Guid("3b91cc7e-c889-47c3-9cc3-b645c7175698"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6834),
                            DoctorId = new Guid("ef0222ff-5282-4b29-a62f-71d853c0aaff"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            Record = "Medical record 24 for patient e073a299-2f0c-4584-bf4c-2278e935cdd8 and doctor ef0222ff-5282-4b29-a62f-71d853c0aaff",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6835)
                        },
                        new
                        {
                            Id = new Guid("7edef27a-7feb-45fe-a297-68fc46908921"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6845),
                            DoctorId = new Guid("63ada4f7-602e-4452-8b87-37ca17b66de8"),
                            PatientId = new Guid("f4982d4f-f4dc-4268-bd99-1327918ad120"),
                            Record = "Medical record 25 for patient f4982d4f-f4dc-4268-bd99-1327918ad120 and doctor 63ada4f7-602e-4452-8b87-37ca17b66de8",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6846)
                        },
                        new
                        {
                            Id = new Guid("e478d4f9-53c2-4fd4-9728-648fe750f13a"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6855),
                            DoctorId = new Guid("e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3"),
                            PatientId = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            Record = "Medical record 26 for patient af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8 and doctor e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6856)
                        },
                        new
                        {
                            Id = new Guid("9e91cf2a-78d8-49a6-bd01-1e89b9b51ddd"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6909),
                            DoctorId = new Guid("1345f6de-2771-46d4-9f77-a4e05956c87e"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            Record = "Medical record 27 for patient 293a3eb3-7212-424a-bec5-d6b37f51841c and doctor 1345f6de-2771-46d4-9f77-a4e05956c87e",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6910)
                        },
                        new
                        {
                            Id = new Guid("2e7251c3-67f1-44b5-b144-85b0fbd6658a"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6919),
                            DoctorId = new Guid("ceb037f8-430e-43e5-a394-786daf2891f2"),
                            PatientId = new Guid("bf2bae64-5991-4ca2-8231-6083c7e009ae"),
                            Record = "Medical record 28 for patient bf2bae64-5991-4ca2-8231-6083c7e009ae and doctor ceb037f8-430e-43e5-a394-786daf2891f2",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6920)
                        },
                        new
                        {
                            Id = new Guid("e73d1adb-dabb-4486-b8c4-ad7dd35b7a8a"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6928),
                            DoctorId = new Guid("9494b0d4-ae59-4812-9b25-05fee61fc6e5"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            Record = "Medical record 29 for patient 0f9e953b-5402-42f6-ab5e-3badc7ea1309 and doctor 9494b0d4-ae59-4812-9b25-05fee61fc6e5",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6929)
                        },
                        new
                        {
                            Id = new Guid("d4f0c5e3-f275-4317-9591-24e3a348299a"),
                            CreatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6937),
                            DoctorId = new Guid("e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3"),
                            PatientId = new Guid("bf2bae64-5991-4ca2-8231-6083c7e009ae"),
                            Record = "Medical record 30 for patient bf2bae64-5991-4ca2-8231-6083c7e009ae and doctor e43570fe-4aa4-4a9b-abc2-e6ae573ba2a3",
                            UpdatedAt = new DateTime(2024, 6, 10, 8, 26, 48, 855, DateTimeKind.Utc).AddTicks(6938)
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InsurancePolicyNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("PatientEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1991, 3, 4),
                            Email = "ava.white0@aol.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "457438627",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-111-279-5968"
                        },
                        new
                        {
                            Id = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1968, 7, 9),
                            Email = "ethan.jackson7@outlook.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "559517151",
                            InsuranceProvider = "Molina Healthcare",
                            PhoneNumber = "+1-222-840-4085"
                        },
                        new
                        {
                            Id = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1994, 6, 18),
                            Email = "ethan.jackson2@hotmail.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "809307597",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-333-664-5474"
                        },
                        new
                        {
                            Id = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            AddressId = 23L,
                            BirthDate = new DateOnly(1968, 10, 10),
                            Email = "ethan.jackson4@gmail.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "122785605",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-111-146-3560"
                        },
                        new
                        {
                            Id = new Guid("87e46f1c-885c-442e-b445-8d734797deeb"),
                            AddressId = 7L,
                            BirthDate = new DateOnly(1954, 10, 22),
                            Email = "amelia.clark3@outlook.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "498497902",
                            InsuranceProvider = "Anthem",
                            PhoneNumber = "+1-111-910-2133"
                        },
                        new
                        {
                            Id = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1973, 12, 27),
                            Email = "mason.harris2@outlook.com",
                            FullName = "Mason Harris",
                            InsurancePolicyNumber = "141716852",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-111-733-6282"
                        },
                        new
                        {
                            Id = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1990, 11, 6),
                            Email = "amelia.clark3@gmail.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "159637843",
                            InsuranceProvider = "Aetna",
                            PhoneNumber = "+1-444-950-4514"
                        },
                        new
                        {
                            Id = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            AddressId = 8L,
                            BirthDate = new DateOnly(1982, 9, 10),
                            Email = "mason.harris5@outlook.com",
                            FullName = "Mason Harris",
                            InsurancePolicyNumber = "738630681",
                            InsuranceProvider = "Oscar Health",
                            PhoneNumber = "+1-222-749-9011"
                        },
                        new
                        {
                            Id = new Guid("bf2bae64-5991-4ca2-8231-6083c7e009ae"),
                            AddressId = 5L,
                            BirthDate = new DateOnly(1963, 8, 25),
                            Email = "sophia.taylor2@outlook.com",
                            FullName = "Sophia Taylor",
                            InsurancePolicyNumber = "738055621",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-333-337-1587"
                        },
                        new
                        {
                            Id = new Guid("589b5b02-38e4-4c53-a813-dd5021f6da39"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1994, 10, 18),
                            Email = "daniel.johnson4@aol.com",
                            FullName = "Daniel Johnson",
                            InsurancePolicyNumber = "566915016",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-111-494-3164"
                        },
                        new
                        {
                            Id = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            AddressId = 17L,
                            BirthDate = new DateOnly(1959, 3, 15),
                            Email = "sophia.taylor3@yahoo.com",
                            FullName = "Sophia Taylor",
                            InsurancePolicyNumber = "112118029",
                            InsuranceProvider = "Oscar Health",
                            PhoneNumber = "+1-222-296-3129"
                        },
                        new
                        {
                            Id = new Guid("f4982d4f-f4dc-4268-bd99-1327918ad120"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1971, 1, 11),
                            Email = "amelia.clark9@hotmail.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "217106838",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-111-359-7582"
                        },
                        new
                        {
                            Id = new Guid("00fed484-9f9a-4339-bc08-d3c5e9467801"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1974, 8, 20),
                            Email = "amelia.clark8@outlook.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "783225190",
                            InsuranceProvider = "Aetna",
                            PhoneNumber = "+1-444-927-7906"
                        },
                        new
                        {
                            Id = new Guid("8fb4f8c8-32d2-4cba-8fc5-33463f65fffa"),
                            AddressId = 18L,
                            BirthDate = new DateOnly(1990, 9, 12),
                            Email = "ava.white1@outlook.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "366797850",
                            InsuranceProvider = "Aetna",
                            PhoneNumber = "+1-222-545-2774"
                        },
                        new
                        {
                            Id = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            AddressId = 8L,
                            BirthDate = new DateOnly(1958, 2, 12),
                            Email = "ava.white9@aol.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "596000616",
                            InsuranceProvider = "Friday Health Plans",
                            PhoneNumber = "+1-333-854-1552"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("SubscriptionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MedicalRecordId = new Guid("08dffb4a-2a7e-47a3-98b3-0caa774a297a"),
                            PatientId = new Guid("8fb4f8c8-32d2-4cba-8fc5-33463f65fffa"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 2L,
                            MedicalRecordId = new Guid("25aaf1c2-4e2b-4946-b2f4-f2034e8002de"),
                            PatientId = new Guid("00fed484-9f9a-4339-bc08-d3c5e9467801"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 3L,
                            MedicalRecordId = new Guid("43c2d659-876f-4d60-b974-62778c8bdf8f"),
                            PatientId = new Guid("bf2bae64-5991-4ca2-8231-6083c7e009ae"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 4L,
                            MedicalRecordId = new Guid("43c2d659-876f-4d60-b974-62778c8bdf8f"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 5L,
                            MedicalRecordId = new Guid("692f03b9-ffcc-4a1e-96f8-2dd0e802023d"),
                            PatientId = new Guid("589b5b02-38e4-4c53-a813-dd5021f6da39"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 6L,
                            MedicalRecordId = new Guid("8c69d425-f59a-4770-a495-5a47d3225e4b"),
                            PatientId = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 7L,
                            MedicalRecordId = new Guid("9cd0a48c-8bab-4ccb-a0e1-f6a01d4acfbf"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 8L,
                            MedicalRecordId = new Guid("e478d4f9-53c2-4fd4-9728-648fe750f13a"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 9L,
                            MedicalRecordId = new Guid("43c2d659-876f-4d60-b974-62778c8bdf8f"),
                            PatientId = new Guid("87e46f1c-885c-442e-b445-8d734797deeb"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 10L,
                            MedicalRecordId = new Guid("4046602e-2e70-469f-8b56-096a360bd0ff"),
                            PatientId = new Guid("589b5b02-38e4-4c53-a813-dd5021f6da39"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 11L,
                            MedicalRecordId = new Guid("3b91cc7e-c889-47c3-9cc3-b645c7175698"),
                            PatientId = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 12L,
                            MedicalRecordId = new Guid("43c2d659-876f-4d60-b974-62778c8bdf8f"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 13L,
                            MedicalRecordId = new Guid("8c69d425-f59a-4770-a495-5a47d3225e4b"),
                            PatientId = new Guid("589b5b02-38e4-4c53-a813-dd5021f6da39"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 14L,
                            MedicalRecordId = new Guid("e73d1adb-dabb-4486-b8c4-ad7dd35b7a8a"),
                            PatientId = new Guid("f4982d4f-f4dc-4268-bd99-1327918ad120"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 15L,
                            MedicalRecordId = new Guid("043d5d32-578b-4281-85c4-948ba1b8d48c"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 16L,
                            MedicalRecordId = new Guid("7edef27a-7feb-45fe-a297-68fc46908921"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 17L,
                            MedicalRecordId = new Guid("043d5d32-578b-4281-85c4-948ba1b8d48c"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 18L,
                            MedicalRecordId = new Guid("9e91cf2a-78d8-49a6-bd01-1e89b9b51ddd"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 19L,
                            MedicalRecordId = new Guid("7edef27a-7feb-45fe-a297-68fc46908921"),
                            PatientId = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 20L,
                            MedicalRecordId = new Guid("043d5d32-578b-4281-85c4-948ba1b8d48c"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 21L,
                            MedicalRecordId = new Guid("eaeca881-df6d-441d-a31a-af0ee0bbfaa1"),
                            PatientId = new Guid("f4982d4f-f4dc-4268-bd99-1327918ad120"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 22L,
                            MedicalRecordId = new Guid("08dffb4a-2a7e-47a3-98b3-0caa774a297a"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 23L,
                            MedicalRecordId = new Guid("9e91cf2a-78d8-49a6-bd01-1e89b9b51ddd"),
                            PatientId = new Guid("87e46f1c-885c-442e-b445-8d734797deeb"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 24L,
                            MedicalRecordId = new Guid("25aaf1c2-4e2b-4946-b2f4-f2034e8002de"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 25L,
                            MedicalRecordId = new Guid("9e91cf2a-78d8-49a6-bd01-1e89b9b51ddd"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 26L,
                            MedicalRecordId = new Guid("33111f91-72f3-4287-a135-e8c3935e51c3"),
                            PatientId = new Guid("00fed484-9f9a-4339-bc08-d3c5e9467801"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 27L,
                            MedicalRecordId = new Guid("3037466f-e974-48c8-98f2-fb823ba1a833"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 28L,
                            MedicalRecordId = new Guid("90252700-eb4c-441a-b1fa-cf68e16dd826"),
                            PatientId = new Guid("ed2b29cc-0fa4-42dc-b373-e3800af239ef"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 29L,
                            MedicalRecordId = new Guid("25aaf1c2-4e2b-4946-b2f4-f2034e8002de"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 30L,
                            MedicalRecordId = new Guid("08dffb4a-2a7e-47a3-98b3-0caa774a297a"),
                            PatientId = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 31L,
                            MedicalRecordId = new Guid("90252700-eb4c-441a-b1fa-cf68e16dd826"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 32L,
                            MedicalRecordId = new Guid("08dffb4a-2a7e-47a3-98b3-0caa774a297a"),
                            PatientId = new Guid("6b036ff0-f402-489e-bad7-f88dd8f23a81"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 33L,
                            MedicalRecordId = new Guid("5e3c7a5e-9d95-4200-8c4f-1bec92a0aafa"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 34L,
                            MedicalRecordId = new Guid("7c177960-96ae-4418-a3dc-3e42cf399ec0"),
                            PatientId = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 35L,
                            MedicalRecordId = new Guid("e478d4f9-53c2-4fd4-9728-648fe750f13a"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 36L,
                            MedicalRecordId = new Guid("6eb8aa5b-33b8-4c99-9e04-0af0be9cda0c"),
                            PatientId = new Guid("460dbf3b-0312-4da5-895e-86834eb43b43"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 37L,
                            MedicalRecordId = new Guid("9cd0a48c-8bab-4ccb-a0e1-f6a01d4acfbf"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 38L,
                            MedicalRecordId = new Guid("90252700-eb4c-441a-b1fa-cf68e16dd826"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 39L,
                            MedicalRecordId = new Guid("cc832aa3-44ae-4310-ae9b-3b08ec8fdcf9"),
                            PatientId = new Guid("af5eb748-e0fa-4fb7-8b0f-6c40ae19e3c8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 40L,
                            MedicalRecordId = new Guid("5e3c7a5e-9d95-4200-8c4f-1bec92a0aafa"),
                            PatientId = new Guid("00fed484-9f9a-4339-bc08-d3c5e9467801"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 41L,
                            MedicalRecordId = new Guid("8c69d425-f59a-4770-a495-5a47d3225e4b"),
                            PatientId = new Guid("a14e0b01-78d2-43bb-9c4e-e9075c3a7fa0"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 42L,
                            MedicalRecordId = new Guid("e607ebfa-fa1f-48d0-833b-b848ea923eca"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 43L,
                            MedicalRecordId = new Guid("692f03b9-ffcc-4a1e-96f8-2dd0e802023d"),
                            PatientId = new Guid("00fed484-9f9a-4339-bc08-d3c5e9467801"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 44L,
                            MedicalRecordId = new Guid("3b91cc7e-c889-47c3-9cc3-b645c7175698"),
                            PatientId = new Guid("910c3e7e-a55f-4844-b5cd-ce831e0fa095"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 45L,
                            MedicalRecordId = new Guid("7c177960-96ae-4418-a3dc-3e42cf399ec0"),
                            PatientId = new Guid("589b5b02-38e4-4c53-a813-dd5021f6da39"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 46L,
                            MedicalRecordId = new Guid("e478d4f9-53c2-4fd4-9728-648fe750f13a"),
                            PatientId = new Guid("8fb4f8c8-32d2-4cba-8fc5-33463f65fffa"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 47L,
                            MedicalRecordId = new Guid("09a59ed7-016a-4fe2-a030-d77db56e53f1"),
                            PatientId = new Guid("0f9e953b-5402-42f6-ab5e-3badc7ea1309"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 48L,
                            MedicalRecordId = new Guid("8c69d425-f59a-4770-a495-5a47d3225e4b"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 49L,
                            MedicalRecordId = new Guid("6893e409-cd81-443d-93cf-ce5f962f2412"),
                            PatientId = new Guid("e073a299-2f0c-4584-bf4c-2278e935cdd8"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 50L,
                            MedicalRecordId = new Guid("4a2c65cf-e17d-404f-9795-bd72fd725375"),
                            PatientId = new Guid("293a3eb3-7212-424a-bec5-d6b37f51841c"),
                            SubscriptionType = "Observer"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Doctors")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.DoctorEntity", "DoctorEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DoctorEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Patients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", "MedicalRecordEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecordEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
