// <auto-generated />

#nullable disable

using MedicalDocumentationManager.Database.Contexts;
using MedicalDocumentationManager.Database.Contexts.Implementations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MedicalDocumentationManager.Database.Migrations
{
    [DbContext(typeof(MedicalDocumentationManagerDbContext))]
    [Migration("20240608124429_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressEntities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Los Angeles",
                            State = "IL",
                            Street = "Cedar Ln",
                            Zip = "54403"
                        },
                        new
                        {
                            Id = 2L,
                            City = "San Antonio",
                            State = "TX",
                            Street = "Sunset Blvd",
                            Zip = "40323"
                        },
                        new
                        {
                            Id = 3L,
                            City = "San Jose",
                            State = "CA",
                            Street = "Maple Ave",
                            Zip = "77157"
                        },
                        new
                        {
                            Id = 4L,
                            City = "Philadelphia",
                            State = "TX",
                            Street = "Pine St",
                            Zip = "61935"
                        },
                        new
                        {
                            Id = 5L,
                            City = "Los Angeles",
                            State = "IL",
                            Street = "Main St",
                            Zip = "78857"
                        },
                        new
                        {
                            Id = 6L,
                            City = "Los Angeles",
                            State = "AZ",
                            Street = "Pine St",
                            Zip = "77779"
                        },
                        new
                        {
                            Id = 7L,
                            City = "Phoenix",
                            State = "CA",
                            Street = "Pine St",
                            Zip = "19771"
                        },
                        new
                        {
                            Id = 8L,
                            City = "Dallas",
                            State = "PA",
                            Street = "Pine St",
                            Zip = "36207"
                        },
                        new
                        {
                            Id = 9L,
                            City = "San Antonio",
                            State = "TX",
                            Street = "Pine St",
                            Zip = "20326"
                        },
                        new
                        {
                            Id = 10L,
                            City = "Dallas",
                            State = "NY",
                            Street = "Highland Ave",
                            Zip = "40541"
                        },
                        new
                        {
                            Id = 11L,
                            City = "Los Angeles",
                            State = "PA",
                            Street = "Washington Ave",
                            Zip = "94620"
                        },
                        new
                        {
                            Id = 12L,
                            City = "Los Angeles",
                            State = "CA",
                            Street = "Broadway",
                            Zip = "57361"
                        },
                        new
                        {
                            Id = 13L,
                            City = "Dallas",
                            State = "IL",
                            Street = "Pine St",
                            Zip = "41357"
                        },
                        new
                        {
                            Id = 14L,
                            City = "Phoenix",
                            State = "PA",
                            Street = "Washington Ave",
                            Zip = "45166"
                        },
                        new
                        {
                            Id = 15L,
                            City = "Dallas",
                            State = "CA",
                            Street = "Pine St",
                            Zip = "12933"
                        },
                        new
                        {
                            Id = 16L,
                            City = "San Jose",
                            State = "PA",
                            Street = "Washington Ave",
                            Zip = "97224"
                        },
                        new
                        {
                            Id = 17L,
                            City = "Chicago",
                            State = "TX",
                            Street = "Broadway",
                            Zip = "77988"
                        },
                        new
                        {
                            Id = 18L,
                            City = "New York",
                            State = "TX",
                            Street = "Highland Ave",
                            Zip = "59833"
                        },
                        new
                        {
                            Id = 19L,
                            City = "Phoenix",
                            State = "TX",
                            Street = "Elm St",
                            Zip = "74098"
                        },
                        new
                        {
                            Id = 20L,
                            City = "Los Angeles",
                            State = "TX",
                            Street = "Washington Ave",
                            Zip = "91171"
                        },
                        new
                        {
                            Id = 21L,
                            City = "Philadelphia",
                            State = "CA",
                            Street = "Pine St",
                            Zip = "37646"
                        },
                        new
                        {
                            Id = 22L,
                            City = "Phoenix",
                            State = "CA",
                            Street = "Elm St",
                            Zip = "85520"
                        },
                        new
                        {
                            Id = 23L,
                            City = "San Antonio",
                            State = "AZ",
                            Street = "Highland Ave",
                            Zip = "38145"
                        },
                        new
                        {
                            Id = 24L,
                            City = "Houston",
                            State = "PA",
                            Street = "Sunset Blvd",
                            Zip = "74299"
                        },
                        new
                        {
                            Id = 25L,
                            City = "Los Angeles",
                            State = "TX",
                            Street = "Oak St",
                            Zip = "48495"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExperienceInYears")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("DoctorEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("214683bd-14f0-49cd-a03f-043b1c754fd4"),
                            AddressId = 15L,
                            BirthDate = new DateOnly(1956, 3, 19),
                            Education = "Medical Degree",
                            Email = "emily.johnson7@yahoo.com",
                            ExperienceInYears = 20L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-555-434-1791",
                            RoomNumber = "B-631",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("f8cf402f-174d-4383-8311-9c10e3a5ae29"),
                            AddressId = 21L,
                            BirthDate = new DateOnly(1970, 5, 2),
                            Education = "Medical Degree",
                            Email = "james.jones5@yahoo.com",
                            ExperienceInYears = 5L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-999-633-4994",
                            RoomNumber = "B-870",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("02fc69ec-c9b2-4bc9-aa83-2ab764d17e12"),
                            AddressId = 19L,
                            BirthDate = new DateOnly(1997, 2, 7),
                            Education = "Medical Degree",
                            Email = "emma.brown4@aol.com",
                            ExperienceInYears = 4L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-666-781-2219",
                            RoomNumber = "D-429",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("7a18f5d6-6ed2-47de-9be6-774a85d3f842"),
                            AddressId = 11L,
                            BirthDate = new DateOnly(1964, 10, 5),
                            Education = "Medical Degree",
                            Email = "emily.johnson0@aol.com",
                            ExperienceInYears = 10L,
                            FullName = "Emily Johnson",
                            PhoneNumber = "+1-666-142-2922",
                            RoomNumber = "A-270",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("fc21f2ff-e569-4fc7-a635-c6069f64e043"),
                            AddressId = 23L,
                            BirthDate = new DateOnly(1971, 12, 20),
                            Education = "Medical Degree",
                            Email = "james.jones9@yahoo.com",
                            ExperienceInYears = 24L,
                            FullName = "James Jones",
                            PhoneNumber = "+1-555-577-1048",
                            RoomNumber = "E-104",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("adb7f2bf-3f3b-4693-ade2-0367c23238db"),
                            AddressId = 17L,
                            BirthDate = new DateOnly(1957, 3, 24),
                            Education = "Medical Degree",
                            Email = "michael.williams5@gmail.com",
                            ExperienceInYears = 10L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-555-983-7440",
                            RoomNumber = "D-506",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("55c2dd3d-fa52-4f72-b63f-8442105f2b22"),
                            AddressId = 23L,
                            BirthDate = new DateOnly(1976, 5, 7),
                            Education = "Medical Degree",
                            Email = "john.smith9@aol.com",
                            ExperienceInYears = 22L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-999-159-7363",
                            RoomNumber = "E-882",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("fa88ccfd-d5a9-41fd-a5f3-975280ea1c9f"),
                            AddressId = 5L,
                            BirthDate = new DateOnly(1955, 8, 13),
                            Education = "Medical Degree",
                            Email = "emma.brown4@gmail.com",
                            ExperienceInYears = 12L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-888-287-8516",
                            RoomNumber = "D-273",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = new Guid("a862d15f-7651-4c0a-8a6f-58b39d0c7c35"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1984, 10, 5),
                            Education = "Medical Degree",
                            Email = "john.smith3@aol.com",
                            ExperienceInYears = 19L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-777-634-6023",
                            RoomNumber = "E-687",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("857d323a-6fb7-4751-a8c2-6338a98389bc"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1983, 1, 25),
                            Education = "Medical Degree",
                            Email = "michael.williams4@hotmail.com",
                            ExperienceInYears = 13L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-555-378-1618",
                            RoomNumber = "D-517",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1991, 11, 26),
                            Education = "Medical Degree",
                            Email = "john.smith1@gmail.com",
                            ExperienceInYears = 19L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-999-852-2263",
                            RoomNumber = "E-853",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("4c5101df-9fd4-42ef-a2a6-30757fc0c78e"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1974, 7, 5),
                            Education = "Medical Degree",
                            Email = "michael.williams1@yahoo.com",
                            ExperienceInYears = 13L,
                            FullName = "Michael Williams",
                            PhoneNumber = "+1-888-208-3170",
                            RoomNumber = "A-618",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("6a81a708-8a8c-4166-832d-e8b2bbf42579"),
                            AddressId = 17L,
                            BirthDate = new DateOnly(1962, 3, 16),
                            Education = "Medical Degree",
                            Email = "john.smith7@aol.com",
                            ExperienceInYears = 16L,
                            FullName = "John Smith",
                            PhoneNumber = "+1-999-154-5732",
                            RoomNumber = "B-929",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = new Guid("accf60ef-aa52-4318-9a38-413b26c02acc"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1996, 6, 3),
                            Education = "Medical Degree",
                            Email = "emma.brown3@aol.com",
                            ExperienceInYears = 5L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-777-848-8767",
                            RoomNumber = "D-639",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("7a42e927-9837-40ae-819b-dfca4058a3df"),
                            AddressId = 2L,
                            BirthDate = new DateOnly(1996, 10, 4),
                            Education = "Medical Degree",
                            Email = "emma.brown1@outlook.com",
                            ExperienceInYears = 25L,
                            FullName = "Emma Brown",
                            PhoneNumber = "+1-555-303-3381",
                            RoomNumber = "C-417",
                            Specialization = "Orthopedics"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Record")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecordEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("870f2507-20bc-40aa-a613-407e88e6a1ba"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7960),
                            DoctorId = new Guid("214683bd-14f0-49cd-a03f-043b1c754fd4"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            Record = "Medical record 1 for patient 7ed2c8b5-4b08-4414-8c76-516f46c5a937 and doctor 214683bd-14f0-49cd-a03f-043b1c754fd4",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7961)
                        },
                        new
                        {
                            Id = new Guid("502905cd-eebb-4cc8-992e-a3633ca2a2fb"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7972),
                            DoctorId = new Guid("accf60ef-aa52-4318-9a38-413b26c02acc"),
                            PatientId = new Guid("3606c837-ae0d-46b7-ad9a-6fc2c866715a"),
                            Record = "Medical record 2 for patient 3606c837-ae0d-46b7-ad9a-6fc2c866715a and doctor accf60ef-aa52-4318-9a38-413b26c02acc",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7972)
                        },
                        new
                        {
                            Id = new Guid("40e50140-66d2-4e35-bc6b-164c75ee3329"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7980),
                            DoctorId = new Guid("adb7f2bf-3f3b-4693-ade2-0367c23238db"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            Record = "Medical record 3 for patient 12db27b5-7019-4077-a1c4-03b29e9e71d7 and doctor adb7f2bf-3f3b-4693-ade2-0367c23238db",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7981)
                        },
                        new
                        {
                            Id = new Guid("6dc4d648-8ab0-4f62-ba16-a7aed239f9bd"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7989),
                            DoctorId = new Guid("02fc69ec-c9b2-4bc9-aa83-2ab764d17e12"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            Record = "Medical record 4 for patient aa8e7cab-6c7e-446a-98ea-f5c8564099a4 and doctor 02fc69ec-c9b2-4bc9-aa83-2ab764d17e12",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7989)
                        },
                        new
                        {
                            Id = new Guid("ce0f1789-fa24-4e66-a935-00f0ed7d724b"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7997),
                            DoctorId = new Guid("6a81a708-8a8c-4166-832d-e8b2bbf42579"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            Record = "Medical record 5 for patient dd161b06-c857-4691-8c7a-47e83a5c4993 and doctor 6a81a708-8a8c-4166-832d-e8b2bbf42579",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(7998)
                        },
                        new
                        {
                            Id = new Guid("b50fc554-4110-4887-b2d9-90e9b242da75"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8011),
                            DoctorId = new Guid("fa88ccfd-d5a9-41fd-a5f3-975280ea1c9f"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            Record = "Medical record 6 for patient e465c73a-da65-4979-8ca4-c0042cc18c06 and doctor fa88ccfd-d5a9-41fd-a5f3-975280ea1c9f",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8012)
                        },
                        new
                        {
                            Id = new Guid("9446f4a3-93b7-4b3f-976b-2b8b9e657da5"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8019),
                            DoctorId = new Guid("02fc69ec-c9b2-4bc9-aa83-2ab764d17e12"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 7 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor 02fc69ec-c9b2-4bc9-aa83-2ab764d17e12",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8019)
                        },
                        new
                        {
                            Id = new Guid("f4573ca4-d36f-4d21-beeb-629b01628d39"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8026),
                            DoctorId = new Guid("f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            Record = "Medical record 8 for patient 12db27b5-7019-4077-a1c4-03b29e9e71d7 and doctor f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8027)
                        },
                        new
                        {
                            Id = new Guid("00f9a2f4-afbf-41e9-87dc-70ea1a3ea8a9"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8033),
                            DoctorId = new Guid("adb7f2bf-3f3b-4693-ade2-0367c23238db"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 9 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor adb7f2bf-3f3b-4693-ade2-0367c23238db",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8033)
                        },
                        new
                        {
                            Id = new Guid("8b80619b-eff1-4dd9-83ae-cfdacf1e142d"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8042),
                            DoctorId = new Guid("7a42e927-9837-40ae-819b-dfca4058a3df"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 10 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor 7a42e927-9837-40ae-819b-dfca4058a3df",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8042)
                        },
                        new
                        {
                            Id = new Guid("8741d404-bf5f-4768-bd05-1a0e6e562457"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8048),
                            DoctorId = new Guid("7a42e927-9837-40ae-819b-dfca4058a3df"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            Record = "Medical record 11 for patient e465c73a-da65-4979-8ca4-c0042cc18c06 and doctor 7a42e927-9837-40ae-819b-dfca4058a3df",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8049)
                        },
                        new
                        {
                            Id = new Guid("313f3635-3e70-47c5-b515-e536522ab881"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8056),
                            DoctorId = new Guid("f8cf402f-174d-4383-8311-9c10e3a5ae29"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            Record = "Medical record 12 for patient 7ed2c8b5-4b08-4414-8c76-516f46c5a937 and doctor f8cf402f-174d-4383-8311-9c10e3a5ae29",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8057)
                        },
                        new
                        {
                            Id = new Guid("2bb5242b-205c-4626-a5d1-59bddbb74335"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8072),
                            DoctorId = new Guid("214683bd-14f0-49cd-a03f-043b1c754fd4"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 13 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor 214683bd-14f0-49cd-a03f-043b1c754fd4",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8072)
                        },
                        new
                        {
                            Id = new Guid("f785ae7d-488a-4544-8066-775ea77f187b"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8081),
                            DoctorId = new Guid("f8cf402f-174d-4383-8311-9c10e3a5ae29"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            Record = "Medical record 14 for patient 7ed2c8b5-4b08-4414-8c76-516f46c5a937 and doctor f8cf402f-174d-4383-8311-9c10e3a5ae29",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8082)
                        },
                        new
                        {
                            Id = new Guid("6f5bda39-07c0-43fd-bdea-3b1a8144f8de"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8089),
                            DoctorId = new Guid("adb7f2bf-3f3b-4693-ade2-0367c23238db"),
                            PatientId = new Guid("3606c837-ae0d-46b7-ad9a-6fc2c866715a"),
                            Record = "Medical record 15 for patient 3606c837-ae0d-46b7-ad9a-6fc2c866715a and doctor adb7f2bf-3f3b-4693-ade2-0367c23238db",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8089)
                        },
                        new
                        {
                            Id = new Guid("2f644c81-241e-49ea-aec9-043a89caa107"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8095),
                            DoctorId = new Guid("f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 16 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8096)
                        },
                        new
                        {
                            Id = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8102),
                            DoctorId = new Guid("214683bd-14f0-49cd-a03f-043b1c754fd4"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            Record = "Medical record 17 for patient 12db27b5-7019-4077-a1c4-03b29e9e71d7 and doctor 214683bd-14f0-49cd-a03f-043b1c754fd4",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8103)
                        },
                        new
                        {
                            Id = new Guid("ec5ed62f-12dd-48de-a548-76c8b55f8f92"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8111),
                            DoctorId = new Guid("fc21f2ff-e569-4fc7-a635-c6069f64e043"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            Record = "Medical record 18 for patient dd161b06-c857-4691-8c7a-47e83a5c4993 and doctor fc21f2ff-e569-4fc7-a635-c6069f64e043",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8112)
                        },
                        new
                        {
                            Id = new Guid("34b867d1-ed38-4c6d-ace0-33784526f18c"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8119),
                            DoctorId = new Guid("accf60ef-aa52-4318-9a38-413b26c02acc"),
                            PatientId = new Guid("8042d801-bdc4-4dca-879d-ee57ee45cb9e"),
                            Record = "Medical record 19 for patient 8042d801-bdc4-4dca-879d-ee57ee45cb9e and doctor accf60ef-aa52-4318-9a38-413b26c02acc",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8119)
                        },
                        new
                        {
                            Id = new Guid("255d4a8a-b657-4e4e-b595-265f56584b11"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8126),
                            DoctorId = new Guid("f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de"),
                            PatientId = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            Record = "Medical record 20 for patient c24f9152-fb5d-4df3-b752-c713506c2b7a and doctor f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8126)
                        },
                        new
                        {
                            Id = new Guid("1eba5bba-673a-4d55-baf4-39a3d711c3d3"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8132),
                            DoctorId = new Guid("accf60ef-aa52-4318-9a38-413b26c02acc"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            Record = "Medical record 21 for patient dd161b06-c857-4691-8c7a-47e83a5c4993 and doctor accf60ef-aa52-4318-9a38-413b26c02acc",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8133)
                        },
                        new
                        {
                            Id = new Guid("e7be8d0a-4c55-43f2-977d-f847808c231c"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8142),
                            DoctorId = new Guid("4c5101df-9fd4-42ef-a2a6-30757fc0c78e"),
                            PatientId = new Guid("8042d801-bdc4-4dca-879d-ee57ee45cb9e"),
                            Record = "Medical record 22 for patient 8042d801-bdc4-4dca-879d-ee57ee45cb9e and doctor 4c5101df-9fd4-42ef-a2a6-30757fc0c78e",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8143)
                        },
                        new
                        {
                            Id = new Guid("6cdec137-1db9-4031-b31c-99d86591b0e5"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8151),
                            DoctorId = new Guid("55c2dd3d-fa52-4f72-b63f-8442105f2b22"),
                            PatientId = new Guid("9f5cb4d7-1e3c-49a6-a71f-d9605e18ea6d"),
                            Record = "Medical record 23 for patient 9f5cb4d7-1e3c-49a6-a71f-d9605e18ea6d and doctor 55c2dd3d-fa52-4f72-b63f-8442105f2b22",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8151)
                        },
                        new
                        {
                            Id = new Guid("11492bff-ce05-4b98-9d9f-d2b754329504"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8158),
                            DoctorId = new Guid("f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            Record = "Medical record 24 for patient 643e41eb-9b21-4fab-8f59-668ae46395fa and doctor f2be1eab-3d9f-4ecb-9d3d-eed1a67df0de",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8158)
                        },
                        new
                        {
                            Id = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8164),
                            DoctorId = new Guid("fc21f2ff-e569-4fc7-a635-c6069f64e043"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            Record = "Medical record 25 for patient dd161b06-c857-4691-8c7a-47e83a5c4993 and doctor fc21f2ff-e569-4fc7-a635-c6069f64e043",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8165)
                        },
                        new
                        {
                            Id = new Guid("97a2391b-48d5-42c6-871a-8d9e680aa2ac"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8171),
                            DoctorId = new Guid("f8cf402f-174d-4383-8311-9c10e3a5ae29"),
                            PatientId = new Guid("534bebae-0954-43a8-bb59-064d727e17e7"),
                            Record = "Medical record 26 for patient 534bebae-0954-43a8-bb59-064d727e17e7 and doctor f8cf402f-174d-4383-8311-9c10e3a5ae29",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8172)
                        },
                        new
                        {
                            Id = new Guid("5fcff655-a07f-4aa6-8f7a-bfc2260743c4"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8178),
                            DoctorId = new Guid("02fc69ec-c9b2-4bc9-aa83-2ab764d17e12"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            Record = "Medical record 27 for patient aa8e7cab-6c7e-446a-98ea-f5c8564099a4 and doctor 02fc69ec-c9b2-4bc9-aa83-2ab764d17e12",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8179)
                        },
                        new
                        {
                            Id = new Guid("8a6b4292-e653-436e-81c9-eedec4f78f41"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8185),
                            DoctorId = new Guid("4c5101df-9fd4-42ef-a2a6-30757fc0c78e"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 28 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor 4c5101df-9fd4-42ef-a2a6-30757fc0c78e",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8186)
                        },
                        new
                        {
                            Id = new Guid("2c3ed2bb-afe0-4430-b07f-e5a8a3806268"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8191),
                            DoctorId = new Guid("accf60ef-aa52-4318-9a38-413b26c02acc"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            Record = "Medical record 29 for patient e465c73a-da65-4979-8ca4-c0042cc18c06 and doctor accf60ef-aa52-4318-9a38-413b26c02acc",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8192)
                        },
                        new
                        {
                            Id = new Guid("be4d2840-5126-498b-8390-cfef9e4bcdc3"),
                            CreatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8200),
                            DoctorId = new Guid("f8cf402f-174d-4383-8311-9c10e3a5ae29"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            Record = "Medical record 30 for patient a2d2fc9b-7666-4041-ac73-b05d8217da67 and doctor f8cf402f-174d-4383-8311-9c10e3a5ae29",
                            UpdatedAt = new DateTime(2024, 6, 8, 12, 44, 29, 382, DateTimeKind.Utc).AddTicks(8201)
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsurancePolicyNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsuranceProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InsurancePolicyNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("PatientEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            AddressId = 11L,
                            BirthDate = new DateOnly(1998, 3, 25),
                            Email = "william.wilson1@gmail.com",
                            FullName = "William Wilson",
                            InsurancePolicyNumber = "612878095",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-222-562-9953"
                        },
                        new
                        {
                            Id = new Guid("534bebae-0954-43a8-bb59-064d727e17e7"),
                            AddressId = 6L,
                            BirthDate = new DateOnly(1952, 2, 3),
                            Email = "mason.harris7@hotmail.com",
                            FullName = "Mason Harris",
                            InsurancePolicyNumber = "278016028",
                            InsuranceProvider = "Friday Health Plans",
                            PhoneNumber = "+1-444-505-6073"
                        },
                        new
                        {
                            Id = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            AddressId = 18L,
                            BirthDate = new DateOnly(1957, 8, 18),
                            Email = "ava.white5@yahoo.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "906166069",
                            InsuranceProvider = "Molina Healthcare",
                            PhoneNumber = "+1-444-652-2205"
                        },
                        new
                        {
                            Id = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            AddressId = 11L,
                            BirthDate = new DateOnly(1971, 10, 21),
                            Email = "sophia.taylor6@hotmail.com",
                            FullName = "Sophia Taylor",
                            InsurancePolicyNumber = "216430902",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-333-399-1615"
                        },
                        new
                        {
                            Id = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            AddressId = 9L,
                            BirthDate = new DateOnly(1980, 5, 25),
                            Email = "ethan.jackson9@outlook.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "993340709",
                            InsuranceProvider = "Aetna",
                            PhoneNumber = "+1-444-874-1363"
                        },
                        new
                        {
                            Id = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            AddressId = 19L,
                            BirthDate = new DateOnly(1972, 5, 2),
                            Email = "mason.harris6@hotmail.com",
                            FullName = "Mason Harris",
                            InsurancePolicyNumber = "938503794",
                            InsuranceProvider = "UnitedHealthcare",
                            PhoneNumber = "+1-444-622-8295"
                        },
                        new
                        {
                            Id = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            AddressId = 17L,
                            BirthDate = new DateOnly(1963, 12, 2),
                            Email = "liam.anderson1@hotmail.com",
                            FullName = "Liam Anderson",
                            InsurancePolicyNumber = "256045754",
                            InsuranceProvider = "Bright Health",
                            PhoneNumber = "+1-444-796-8711"
                        },
                        new
                        {
                            Id = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            AddressId = 14L,
                            BirthDate = new DateOnly(1967, 4, 16),
                            Email = "ava.white3@gmail.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "686503722",
                            InsuranceProvider = "Molina Healthcare",
                            PhoneNumber = "+1-333-836-9819"
                        },
                        new
                        {
                            Id = new Guid("3606c837-ae0d-46b7-ad9a-6fc2c866715a"),
                            AddressId = 4L,
                            BirthDate = new DateOnly(1966, 6, 11),
                            Email = "amelia.clark2@yahoo.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "533830533",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-444-372-8019"
                        },
                        new
                        {
                            Id = new Guid("4fbc5155-e9f2-47e4-9cd2-b021726cdd80"),
                            AddressId = 12L,
                            BirthDate = new DateOnly(1961, 10, 11),
                            Email = "mason.harris2@gmail.com",
                            FullName = "Mason Harris",
                            InsurancePolicyNumber = "824191038",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-333-490-1246"
                        },
                        new
                        {
                            Id = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            AddressId = 24L,
                            BirthDate = new DateOnly(1957, 12, 3),
                            Email = "ava.white4@aol.com",
                            FullName = "Ava White",
                            InsurancePolicyNumber = "350814514",
                            InsuranceProvider = "Molina Healthcare",
                            PhoneNumber = "+1-333-582-3226"
                        },
                        new
                        {
                            Id = new Guid("9f5cb4d7-1e3c-49a6-a71f-d9605e18ea6d"),
                            AddressId = 24L,
                            BirthDate = new DateOnly(1974, 8, 8),
                            Email = "isabella.martinez1@outlook.com",
                            FullName = "Isabella Martinez",
                            InsurancePolicyNumber = "126471492",
                            InsuranceProvider = "BlueCross",
                            PhoneNumber = "+1-444-252-7983"
                        },
                        new
                        {
                            Id = new Guid("ec60232f-032e-4b90-b122-33237264cc02"),
                            AddressId = 16L,
                            BirthDate = new DateOnly(1952, 5, 12),
                            Email = "olivia.davis4@hotmail.com",
                            FullName = "Olivia Davis",
                            InsurancePolicyNumber = "360186698",
                            InsuranceProvider = "Oscar Health",
                            PhoneNumber = "+1-444-412-6850"
                        },
                        new
                        {
                            Id = new Guid("ab413ddc-0b02-48e7-b387-436a832f7d44"),
                            AddressId = 8L,
                            BirthDate = new DateOnly(1959, 11, 17),
                            Email = "ethan.jackson4@outlook.com",
                            FullName = "Ethan Jackson",
                            InsurancePolicyNumber = "656990873",
                            InsuranceProvider = "Oxford Health Plans",
                            PhoneNumber = "+1-444-663-4951"
                        },
                        new
                        {
                            Id = new Guid("8042d801-bdc4-4dca-879d-ee57ee45cb9e"),
                            AddressId = 20L,
                            BirthDate = new DateOnly(1950, 9, 1),
                            Email = "amelia.clark7@gmail.com",
                            FullName = "Amelia Clark",
                            InsurancePolicyNumber = "297282585",
                            InsuranceProvider = "Health Net",
                            PhoneNumber = "+1-444-945-4927"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("MedicalRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.ToTable("SubscriptionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedicalRecordId = new Guid("11492bff-ce05-4b98-9d9f-d2b754329504"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 2,
                            MedicalRecordId = new Guid("ec5ed62f-12dd-48de-a548-76c8b55f8f92"),
                            PatientId = new Guid("ab413ddc-0b02-48e7-b387-436a832f7d44"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 3,
                            MedicalRecordId = new Guid("ec5ed62f-12dd-48de-a548-76c8b55f8f92"),
                            PatientId = new Guid("534bebae-0954-43a8-bb59-064d727e17e7"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 4,
                            MedicalRecordId = new Guid("6cdec137-1db9-4031-b31c-99d86591b0e5"),
                            PatientId = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 5,
                            MedicalRecordId = new Guid("6cdec137-1db9-4031-b31c-99d86591b0e5"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 6,
                            MedicalRecordId = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 7,
                            MedicalRecordId = new Guid("40e50140-66d2-4e35-bc6b-164c75ee3329"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 8,
                            MedicalRecordId = new Guid("502905cd-eebb-4cc8-992e-a3633ca2a2fb"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 9,
                            MedicalRecordId = new Guid("34b867d1-ed38-4c6d-ace0-33784526f18c"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 10,
                            MedicalRecordId = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            PatientId = new Guid("ab413ddc-0b02-48e7-b387-436a832f7d44"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 11,
                            MedicalRecordId = new Guid("255d4a8a-b657-4e4e-b595-265f56584b11"),
                            PatientId = new Guid("8042d801-bdc4-4dca-879d-ee57ee45cb9e"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 12,
                            MedicalRecordId = new Guid("2f644c81-241e-49ea-aec9-043a89caa107"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 13,
                            MedicalRecordId = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            PatientId = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 14,
                            MedicalRecordId = new Guid("2f644c81-241e-49ea-aec9-043a89caa107"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 15,
                            MedicalRecordId = new Guid("9446f4a3-93b7-4b3f-976b-2b8b9e657da5"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 16,
                            MedicalRecordId = new Guid("6cdec137-1db9-4031-b31c-99d86591b0e5"),
                            PatientId = new Guid("534bebae-0954-43a8-bb59-064d727e17e7"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 17,
                            MedicalRecordId = new Guid("b50fc554-4110-4887-b2d9-90e9b242da75"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 18,
                            MedicalRecordId = new Guid("ec5ed62f-12dd-48de-a548-76c8b55f8f92"),
                            PatientId = new Guid("4fbc5155-e9f2-47e4-9cd2-b021726cdd80"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 19,
                            MedicalRecordId = new Guid("34b867d1-ed38-4c6d-ace0-33784526f18c"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 20,
                            MedicalRecordId = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            PatientId = new Guid("9f5cb4d7-1e3c-49a6-a71f-d9605e18ea6d"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 21,
                            MedicalRecordId = new Guid("be4d2840-5126-498b-8390-cfef9e4bcdc3"),
                            PatientId = new Guid("9f5cb4d7-1e3c-49a6-a71f-d9605e18ea6d"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 22,
                            MedicalRecordId = new Guid("f4573ca4-d36f-4d21-beeb-629b01628d39"),
                            PatientId = new Guid("8042d801-bdc4-4dca-879d-ee57ee45cb9e"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 23,
                            MedicalRecordId = new Guid("9446f4a3-93b7-4b3f-976b-2b8b9e657da5"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 24,
                            MedicalRecordId = new Guid("ce0f1789-fa24-4e66-a935-00f0ed7d724b"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 25,
                            MedicalRecordId = new Guid("313f3635-3e70-47c5-b515-e536522ab881"),
                            PatientId = new Guid("ec60232f-032e-4b90-b122-33237264cc02"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 26,
                            MedicalRecordId = new Guid("5fcff655-a07f-4aa6-8f7a-bfc2260743c4"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 27,
                            MedicalRecordId = new Guid("f785ae7d-488a-4544-8066-775ea77f187b"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 28,
                            MedicalRecordId = new Guid("5fcff655-a07f-4aa6-8f7a-bfc2260743c4"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 29,
                            MedicalRecordId = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            PatientId = new Guid("643e41eb-9b21-4fab-8f59-668ae46395fa"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 30,
                            MedicalRecordId = new Guid("ce0f1789-fa24-4e66-a935-00f0ed7d724b"),
                            PatientId = new Guid("ec60232f-032e-4b90-b122-33237264cc02"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 31,
                            MedicalRecordId = new Guid("f785ae7d-488a-4544-8066-775ea77f187b"),
                            PatientId = new Guid("4fbc5155-e9f2-47e4-9cd2-b021726cdd80"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 32,
                            MedicalRecordId = new Guid("11492bff-ce05-4b98-9d9f-d2b754329504"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 33,
                            MedicalRecordId = new Guid("ec5ed62f-12dd-48de-a548-76c8b55f8f92"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 34,
                            MedicalRecordId = new Guid("6dc4d648-8ab0-4f62-ba16-a7aed239f9bd"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 35,
                            MedicalRecordId = new Guid("2f644c81-241e-49ea-aec9-043a89caa107"),
                            PatientId = new Guid("534bebae-0954-43a8-bb59-064d727e17e7"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 36,
                            MedicalRecordId = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            PatientId = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 37,
                            MedicalRecordId = new Guid("870f2507-20bc-40aa-a613-407e88e6a1ba"),
                            PatientId = new Guid("a2d2fc9b-7666-4041-ac73-b05d8217da67"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 38,
                            MedicalRecordId = new Guid("1eba5bba-673a-4d55-baf4-39a3d711c3d3"),
                            PatientId = new Guid("ec60232f-032e-4b90-b122-33237264cc02"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 39,
                            MedicalRecordId = new Guid("ce0f1789-fa24-4e66-a935-00f0ed7d724b"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 40,
                            MedicalRecordId = new Guid("9446f4a3-93b7-4b3f-976b-2b8b9e657da5"),
                            PatientId = new Guid("7ed2c8b5-4b08-4414-8c76-516f46c5a937"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 41,
                            MedicalRecordId = new Guid("00f9a2f4-afbf-41e9-87dc-70ea1a3ea8a9"),
                            PatientId = new Guid("c24f9152-fb5d-4df3-b752-c713506c2b7a"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 42,
                            MedicalRecordId = new Guid("502905cd-eebb-4cc8-992e-a3633ca2a2fb"),
                            PatientId = new Guid("3606c837-ae0d-46b7-ad9a-6fc2c866715a"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 43,
                            MedicalRecordId = new Guid("2540134b-a81f-4e04-9f9a-761a339ffbc0"),
                            PatientId = new Guid("12db27b5-7019-4077-a1c4-03b29e9e71d7"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 44,
                            MedicalRecordId = new Guid("97a2391b-48d5-42c6-871a-8d9e680aa2ac"),
                            PatientId = new Guid("dd161b06-c857-4691-8c7a-47e83a5c4993"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 45,
                            MedicalRecordId = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            PatientId = new Guid("ab413ddc-0b02-48e7-b387-436a832f7d44"),
                            SubscriptionType = "Observer"
                        },
                        new
                        {
                            Id = 46,
                            MedicalRecordId = new Guid("f4573ca4-d36f-4d21-beeb-629b01628d39"),
                            PatientId = new Guid("e465c73a-da65-4979-8ca4-c0042cc18c06"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 47,
                            MedicalRecordId = new Guid("2f644c81-241e-49ea-aec9-043a89caa107"),
                            PatientId = new Guid("ec60232f-032e-4b90-b122-33237264cc02"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 48,
                            MedicalRecordId = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            PatientId = new Guid("3606c837-ae0d-46b7-ad9a-6fc2c866715a"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 49,
                            MedicalRecordId = new Guid("6dc4d648-8ab0-4f62-ba16-a7aed239f9bd"),
                            PatientId = new Guid("aa8e7cab-6c7e-446a-98ea-f5c8564099a4"),
                            SubscriptionType = "Notifier"
                        },
                        new
                        {
                            Id = 50,
                            MedicalRecordId = new Guid("96ca3060-29a9-4f74-ad35-f624d940fe1a"),
                            PatientId = new Guid("ab413ddc-0b02-48e7-b387-436a832f7d44"),
                            SubscriptionType = "Observer"
                        });
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Doctors")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.DoctorEntity", "DoctorEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DoctorEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.AddressEntity", "AddressEntity")
                        .WithMany("Patients")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddressEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.SubscriptionEntity", b =>
                {
                    b.HasOne("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", "MedicalRecordEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalDocumentationManager.Database.Entities.PatientEntity", "PatientEntity")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecordEntity");

                    b.Navigation("PatientEntity");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.AddressEntity", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.DoctorEntity", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.MedicalRecordEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("MedicalDocumentationManager.Database.Entities.PatientEntity", b =>
                {
                    b.Navigation("MedicalRecords");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
