using MedicalDocumentationManager.DTOs.RequestsDTOs;

namespace MedicalDocumentationManager.Persistence.Commands.Subscription;

public sealed record CreateSubscriptionCommand(RequestSubscriptionDto RequestSubscriptionDto);